### PR TITLE
feat: add khala and pha into portal

### PR DESCRIPTION
**Pull request by kingsleydon**
**Pull Request Summary**

Add Khala Chain and PHA asset by following https://docs.astar.network/docs/xcm/integration/add-to-portal/

Transfer PHA from Khala to Shiden with `minBridgeAmount` to 0 balance account: 
https://khala.subscan.io/extrinsic/0xb4f5cd76f478304cb4378e43c6f5a80083f6907d61d17316696918cebb320809

Transfer SDN from Khala to Shiden with `minBridgeAmount` to 0 balance account: 
https://khala.subscan.io/extrinsic/2585071-2

Transfer PHA from Shiden to Khala with `minBridgeAmount` to 0 balance account: 
https://shiden.subscan.io/extrinsic/0x67e808721d6a3058a4be42f62fae4ea933ea97e28d9bbe69ed9ae19ac2c3b396

Transfer SDN from Shiden to Khala with `minBridgeAmount` to 0 balance account: 
https://shiden.subscan.io/extrinsic/2603761-2

**Check list**
- [x] adds new feature

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @kingsleydon 
Thank you for your contribution. Looks good to me.
I found  minor issues (kind of weird bug) on the UI side while depositing SDN from Khala to Shiden. 

1. UI doesn't display the correct value at `From Balance`
image

2. UI won't stop the loading animation 
Screenshot 2022-11-08 at 6 35 35 PM

Here is the quick fix for the issues above, could you help update 2 files according to my gist files? You can just copy and paste.

src/hooks/xcm/useXcmBridgeV3.ts 
https://gist.github.com/impelcrypto/28475f63f620b121772355c5a2b63d39#file-usexcmbridgev3-ts-L405

src/modules/xcm/utils.index.ts 
https://gist.github.com/impelcrypto/01bc5d3802c46089b7b8ecc118ea42c8#file-index-ts-L137

**Comment by kingsleydon** [comment]
It's a bit odd, I don't seem to notice these issues when testing locally, but I'll try to fix it later

**Comment by kingsleydon** [comment]
Added a commit included two gist files above and rebased the branch to main

**Review by impelcrypto — APPROVED** [review]
LGTM

**Review by gluneau — APPROVED** [review]
LGTM as well.

**Pull request merged**
