### PR TITLE
Display a dApp tier rank

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

dApp details page update to show the dApp tier rank
image

A dApp tier rank is number from 0 to 10 and it is used to calculate tier rewards. A dApp with a higher rank within the same tier will get more rewards than a dApp with lower rank. More info [here](https://github.com/AstarNetwork/Astar/pull/1240) and [here](https://github.com/AstarNetwork/astar-apps/issues/1305)

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by impelcrypto** [comment]
@bobo-k2 Why 0 for the rank of all the dApps?

**Comment by bobo-k2** [comment]
> @bobo-k2 Why 0 for the rank of all the dApps?
It is because the feature is not live on Astar and Shiden. I made this PR too early.

**Comment by bobo-k2** [comment]
Hi @Kahonnohak I updated the code according to your comments

**Comment by gtg7784** [comment]
> > @bobo-k2 Why 0 for the rank of all the dApps?
> 
> 
> 
> It is because the feature is not live on Astar and Shiden. I made this PR too early.
> 
> 

Is it works now?

**Review by impelcrypto — APPROVED** [review]

**Review by gtg7784 — APPROVED** [review]

**Pull request merged**
