### PR TITLE
feat: added decentralised banner

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: added decentralized banner
  * staging for decentralized banner: astar-portal-melvif4ls-impelcrypto.vercel.app  @Kahonnohak 
* fix: modified styling bugs

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

* feat: added decentralized banner
image

**Fixes**

* fix: modified styling bugs

=Before=

Screenshot 2023-05-19 at 4 04 29 PM

=After=
image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thanks for fixing as well!

- decentralised.portal banner
For Mobile, please make the font size: 12px
Screenshot 2023-05-19 at 11 26 50

- The banners on Asset page
Could you remove the padding from the right please? This might have been the reason why it got broken but please take a look.

Screenshot 2023-05-19 at 11 21 28

**Comment by Kahonnohak** [comment]
> @Kahonnohak Updated. Staging: https://astar-portal-melvif4ls-impelcrypto.vercel.app/astar/assets

Thanks I got 404 (I can see it for 2 seconds) : https://astar-portal-melvif4ls-impelcrypto.vercel.app/


Screenshot 2023-05-19 at 12 05 49

**Comment by impelcrypto** [comment]
@Kahonnohak Have you refreshed your browser after opened the page (that's caused this error)? Maybe try it again?

**Review by Kahonnohak — APPROVED** [review]
Thanks lgtm

**Review by niklabh — APPROVED** [review]

**Pull request merged**
