### PR TITLE
feat: added 'network statuses' section on dashboard page

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: added 'network statuses' and 'Collator' section on dashboard page

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Adds**

* feat: added 'network statuses' and 'Collator' section on dashboard page
* fix: removed version information on the network button
image

 

* Added tooltip when the XCM deposit/withdrawal is disabled (this tooltip can be viewed in production page)

Screenshot 2023-08-07 at 4 40 05 PM

### CODE REVIEW

**Review by gluneau — APPROVED** [review]
The code looks good and the preview works as intended.

**Comment by Kahonnohak** [comment]
Nice work! Two things
- Could you make the text size of the update xx sec ago, 12px please?
- The icon next to collator numbers, could you put it in the centre (of the height) the screenshots are after I have adjusted.
Screenshot 2023-08-07 at 22 19 01
Screenshot 2023-08-07 at 22 19 15

**Comment by impelcrypto** [comment]
@Kahonnohak Updated!

**Review by Kahonnohak — APPROVED** [review]
Great work!

**Pull request merged**
