### PR TITLE
Account unification

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Account unification feature. To contribute create a branch from `feat/account-unification` 

TODO
- [x] account unification logic
- [ ] ui components
- [ ] connect ui components and logic
- [ ] check and fix all token transfer workflows on the portal to support unified accounts

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by impelcrypto** [comment]
@bobo-k2 I've pulled the main branch

**Comment by Kahonnohak** [comment]
@bobo-k2 Please take a look at this? 
Screenshot 2023-09-29 at 09 23 55

**Comment by Kahonnohak** [comment]
**When connected to a substrate wallet**

1) When pressed the Unify Account button on Asset page it gets the error, it should bring the side modal up and this should be the only way to create account.

Screenshot 2023-09-29 at 11 15 46

2) When I go to wallet modal while I am connected to Native, although I don't have Astar account I can already see the button and start creating the unified account. Which is fine, however if no wallet is connected and user doesn't have a unified account, then they cannot do anything. 
- Remove the Astar Account when user doesn't have a unified account - could portal check when user open the modal?
- Keep the Astar Account option shown only when user is connected to Native. (nice to have)

Screenshot 2023-09-29 at 11 30 28

3) Before connecting to EVM it already says I have staking - please remove this

Screenshot 2023-09-29 at 11 19 46


4)After connecting EVM and you know that you have the staking and you cannot unify with the account you choose, then you go back but there is not a way to re-select an account since the EVM seems still be connected. Please disconnect when user pressed the close button.
Screenshot 2023-09-29 at 10 11 20

**Comment by ayumitk** [comment]
@impelcrypto Adjusted the checkbox position ([d1e5375](https://github.com/AstarNetwork/astar-apps/pull/925/commits/d1e537580fc9e338dd2db6fe99ea46022e25073c))
Screenshot 2023-09-29 at 5 25 24 PM

**Comment by Kahonnohak** [comment]
- Please remove the account icon from Astar Network and Shiden Network
Screenshot 2023-10-03 at 12 26 06

- When you first press the account icon with Native account is connected, you will immediately get Metamaks extension, please stop this happen at this modal.
Screenshot 2023-10-03 at 12 27 59

- Please remove Staking warning since at this stage Portal is not connected to EVM, it is fine for a Native to have staking balance.
Screenshot 2023-10-03 at 13 14 58

- And when you do have EVM staking balance like here, there is no way to disconnect from Portal.
-- Please change the button message and disconnect (Close -> Disconnect)
Screenshot 2023-10-03 at 13 32 41

- What is the plan for Shibuya release? If no NFT is going to be added, please change the text to
-- `Account Icon (we are working on adding own NFT as account icon)`
Screenshot 2023-10-03 at 13 22 41


- After account is unified, does user need to refresh by themselves to show the account name changed?
-- Could you change EVM account name please and use Unified account name
-- Could you change the icon too, since okay, it is shibuya but we should since we will give this to community to test out
Screenshot 2023-10-03 at 13 24 47


But yes! I got account unified!!! Great work!!

**Comment by bobo-k2** [comment]
I worked on last point (account name) and plan to close that point

**Comment by Kahonnohak** [comment]
Also sorry, those were hiding in the modal design in Figma, I forgot to mention 🙏!!

1) disclaimer
2) the last modal
Screenshot 2023-10-03 at 20 58 43
Screenshot 2023-10-03 at 20 58 18

**Comment by impelcrypto** [comment]
@bobo-k2 
We need to consider 'Reserved Amount' into Transferable
image

image

**Comment by bobo-k2** [comment]
> @bobo-k2 We need to consider 'Reserved Amount' into Transferable ![image](https://user-

On my side native and evm balances are the same. Can you share steps to reproduce the issue. I don't think we can consider locked amount as transferable because it isn't transferable.

image

image

**Comment by impelcrypto** [comment]
@bobo-k2 
This is my account. The account has staked 10.418SBY on dApps.
https://shibuya.subscan.io/account/WkuMXKG2tLL2T2MLuD7JxzFaLVDFcEpg7JxZirCFbSzeovY

**Review by impelcrypto — APPROVED** [review]

**Comment by Kahonnohak** [comment]
I've found another things

1) After unified, the account still shows only one account. It has to change to unified account profile and it needs to be able to edit.
Screenshot 2023-10-06 at 14 09 49

Screenshot 2023-10-06 at 14 14 18

This is the design
Screenshot 2023-10-06 at 14 20 43


2) As I cannot have xcTokens in EVM at this moment I cannot check but where is the modal that shows all xcTokens to be transferred? I never seen it yet. 

It was unified once 3days ago, and I overrode it today. I did not see the information on modal that would tell me to agree on transferring them.

Screenshot 2023-10-06 at 14 15 13

This is the design
Screenshot 2023-10-06 at 14 20 21

We cannot merge before getting this done, please take a look

**Comment by Kahonnohak** [comment]
Styling
Please also fix this, it happens when the screen is wider, only on Shibuya
Screenshot 2023-10-06 at 14 55 47

**Comment by impelcrypto** [comment]
@Kahonnohak @fiexer 
I've fixed the odd space issue in this [commit](https://github.com/AstarNetwork/astar-apps/pull/925/commits/5f962840a63f81d4b0d1b918d257a7f0d85b1adb).

image

**Comment by Kahonnohak** [comment]
@bobo-k2 most bits are the things we can leave it for later but can we change this MM icon to unified icon?
Screenshot 2023-10-09 at 15 52 35

**Review by ayumitk — APPROVED** [review]

**Review by Kahonnohak — APPROVED** [review]
Great work!!

**Pull request merged**
