### PR TITLE
Create NEET dApp Staking.png

### PR DESCRIPTION
**Pull request by 83971101151178107109116111**
**Pull Request Summary**

> I would like to add NEET promotional card, please.

### CODE REVIEW

**Comment by bobo-k2** [comment]
@83971101151178107109116111 plese create one PR and include all required files there. Thank you

**Comment by 83971101151178107109116111** [comment]
I have added the missing file

**Comment by bobo-k2** [comment]
> I have added the missing file

I still see one file in this PR (2 files expected). You opened 2 PRs. #1320 and #1321. Please close one and make sure to have all changes in single PR

**Comment by 83971101151178107109116111** [comment]
I have fixed the link with the proper one.

**Pull request closed without merging**
