### PR TITLE
fix: support local and custom network

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* Currently the portal is getting configuration data such as ‘EVM endpoint’ from `providerEndpoints` array and `networkIdx` global state, but the array's data structure doesn't work with local and custom network.
Use chainInfo global state to get the chain data instead of `networkIdx` .

* Modified buttons (for EVM deposit case)

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

Custom Network: wss://ws.shiden.bldnodes.org/
=Before=
image

image

image

=After=
image

image

image

### CODE REVIEW

**Comment by hoonsubin** [comment]
bandicam 2022-01-20 18-49-48-091

bandicam 2022-01-20 18-50-09-183

I get the `Custom sig extrinsic calls has been temporarily blocked` message when I connect to Shiden via `wss://rpc.pinknode.io/shiden/explorer`. Do you know why this is happening? I'm not logged in with MetaMask.

**Comment by impelcrypto** [comment]
No, I don't know, but it is the same behavior with the main branch. (I can take a look tomorrow if this is something we should care about).
 
image

**Comment by impelcrypto** [comment]
@hoonsubin Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/228/commits/03e2f4df24cd2eb94023dbdc85177ca4eb8d32e6) commit. Seems like [transfer](https://shiden.subscan.io/extrinsic/1059734-2) succeeded. 

The [comment](https://github.com/AstarNetwork/astar-apps/blob/03e2f4df24cd2eb94023dbdc85177ca4eb8d32e6/src/components/balance/modals/ModalTransferAmount.vue#L184) wrote by @bobo-k2, I hope the commit is fine.

**Review by hoonsubin — APPROVED** [review]
LGTM
All issues were fixed. That comment is outdated.

**Pull request merged**
