### PR TITLE
feat: added lockdrop account UI

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: added lockdrop account UI 
  *  The toggle button appears for the H160 account which mapped SS58 account has more than 0 native token  
  * It works on Shibuya only for now. I'll update it once Astar and Shiden runtime have been updated. CC: @PierreOssun  

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

* feat: added lockdrop account UI 

image

image

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
tested, transaction works! great work!

- The yellow box doesn't seemed to be applied on the UI
- Could you add "Access ends 31 August 2024" on the yellow box please? If the text gets too long its fine to change the font size. 

Screenshot 2024-02-14 at 10 53 24

**Comment by impelcrypto** [comment]
@Kahonnohak 
> It might be better to take them to Asset page since most of them has staking balance they need unlocking first before they can move tokens

Do you mean the portal goes to assets page after users click `Move Funds Now` button?

**Comment by impelcrypto** [comment]
@Kahonnohak Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/1166/commits/dba30e125fabf4be8900a215713eabc1db8aaeb2) commit.

image

**Review by Kahonnohak — APPROVED** [review]
LGTM

**Review by gluneau — APPROVED** [review]
Tested and working

**Pull request merged**
