### PR TITLE
Inflation dashboard

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Added inflation charts to the dashboard
Update the dashboard design

image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]

**Comment by Kahonnohak** [comment]
Looking great @bobo-k2 !!

Apart from the TVL dependant part, could you add
1) Title for the ASTR area. ASTR token utility? but it includes era/block info so my proposal is "$ASTR" or "ASTR Token"
2) Could you adjust the space between here? Cannot really access to the styling for the hover state but if you could adjust in nice way that would be great!
Screenshot 2024-05-25 at 06 19 29

**Review by gtg7784 — APPROVED** [review]
LGTM!

**Comment by bobo-k2** [comment]
> Looking great @bobo-k2 !!
> 
> Apart from the TVL dependant part, could you add
> 
> 1. Title for the ASTR area. ASTR token utility? but it includes era/block info so my proposal is "$ASTR" or "ASTR Token"
> 2. Could you adjust the space between here? Cannot really access to the styling for the hover state but if you could adjust in nice way that would be great!


Thanks @Kahonnohak I updated the code, please re-check the PR

**Review by Kahonnohak — APPROVED** [review]
If you can adjust the giga space between name and percentage in the chart (inflation) would be great but this is connected to other one lets ignore

**Pull request merged**
