### PR TITLE
Dapp staking v3 improvements, part 8

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**
This PR contains the following.

- **Split stake amounts per sub periods**
image

- **Unlock modal**
image

- **Registration page bug fix**
image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@bobo-k2 thanks just one thing - did you change the icons?

- Stake ↓ 
- Unlock ↑
Screenshot 2024-01-24 at 19 44 47


All works and fixed thank you!

**Review by gluneau — APPROVED** [review]
LGTM

**Comment by bobo-k2** [comment]
> @bobo-k2 thanks just one thing - did you change the icons?
> 
> * Stake ↓
> * Unlock ↑

I didn't change intentionally. I will fix.

**Review by impelcrypto — APPROVED** [review]

**Review by ayumitk — APPROVED** [review]

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Pull request merged**
