### PR TITLE
feat: transfer XC20 tokens to the unified SS58 account

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: transfers XC20 tokens to the unified SS58 account
* feat: lists XCM assets on Shibuya (if the account has balance)

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
* feat: transfer XC20 tokens to the unified SS58 account
 
image

* feat: lists XCM assets on Shibuya (if the account has balance)

image

### CODE REVIEW

**Review by gluneau — CHANGES_REQUESTED** [review]
image
There is a bug where if you claim from the faucet while connected with metamask of a unified account.  It's not the unified account who will receive the tokens, but a https://hoonsubin.github.io/evm-substrate-address-converter/ SS58 derived address instead.

**Comment by impelcrypto** [comment]
>  There is a bug where if you claim from the faucet while connected with metamask of a unified account. It's not the unified account who will receive the tokens, but a https://hoonsubin.github.io/evm-substrate-address-converter/ SS58 derived address instead.

Thanks @gluneau 

Maybe it's better to fix the bug in the different PR [here](https://github.com/AstarNetwork/astar-apps/pull/925). 
@bobo-k2 Could you advise which address users should receive faucet? Unified SS58 account or the original H160 address? Should Unified SS58 address pay the gas(fee) for all the transactions signed by MetaMask?

**Comment by impelcrypto** [comment]
@bobo-k2 @gluneau Fixed, please take a look at this [commit](https://github.com/AstarNetwork/astar-apps/pull/944/commits/cfbbef99cd03d32f2c3c2cd34d8ca33db981286e).

**Comment by bobo-k2** [comment]
> > There is a bug where if you claim from the faucet while connected with metamask of a unified account. It's not the unified account who will receive the tokens, but a https://hoonsubin.github.io/evm-substrate-address-converter/ SS58 derived address instead.
> 
> Thanks @gluneau
> 
> Maybe it's better to fix the bug in the different PR [here](https://github.com/AstarNetwork/astar-apps/pull/925). @bobo-k2 Could you advise which address users should receive faucet? Unified SS58 account or the original H160 address? Should Unified SS58 address pay the gas(fee) for all the transactions signed by MetaMask?

When account is unified I believe it doesn't matter which address receives tokens from faucet. The same applies for gas.

**Review by bobo-k2 — APPROVED** [review]

**Pull request merged**
