### PR TITLE
feat: update ERC20 token balance, put MetaMask on top of the wallet list

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* styling: put MetaMask on top of the wallet list
* feat: update ERC20 token balance after sending transaction
* fix: avoid fetching ERC20 tokens in Shibuya
* refactor: `useCbridgeV2.ts`

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Changes**

=Before=

image

=After=
image

### CODE REVIEW

**Review by sirius651 — APPROVED** [review]

**Comment by impelcrypto** [comment]
Hi @hoonsubin @bobo-k2 
Could you help review this PR if you can, please? Thank you!

**Comment by bobo-k2** [comment]
> Hi @hoonsubin @bobo-k2 Could you help review this PR if you can, please? Thank you!

Sure, how urgent it is. I can take a look in couple of hours

**Comment by impelcrypto** [comment]
@bobo-k2 
No worries, I just want to make another PR on top of this PR :)

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
