### PR TITLE
Translate the Astar Portal for Japanese 

### PR DESCRIPTION
**Pull request by tksarah**
**Pull Request Summary**
I translated to Japanese on i18n/ja/index.ts for Astar Portal.
This PR is in accordance with the Astar Ecosystem task "Translate the Astar Portal and keep it up to date."

> Describe what changes this pull request makes to the repository

The "src/i18n/ja/index.ts" is modified to translate in Japanese.

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

This PR changes for Astar Portal.
We would be able to change to Japanese on Astar Portal's settings with this PR.
The translation rate is approximately 97%. This is because there were some things that were difficult to translate into Japanese. Those word or sentence is left as is for now.

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you for your help. I see lots of errors, they are all code formatting mistakes. Could you check them by running below.
Run `yarn dev` to see errors.
Run `yarn lint --fix` to fix errors
Screenshot 2024-01-08 at 09 02 56

**Comment by tksarah** [comment]
Thank you for your review.
I have fixed the errors and then I confirmed "No issues found." by running "yarn dev".

**Review by Kahonnohak — APPROVED** [review]
Thank you! We plan to release this PR on Wednesday!

**Comment by Kahonnohak** [comment]
@tksarah could you create the PR against the hotfix branch please?

**Comment by tksarah** [comment]
I created a PR. How about this? @Kahonnohak

**Comment by Kahonnohak** [comment]
ahh, I am sorry, it wasn't needed at all, so sorry I was thinking of something else, will release tomorrow

**Review by bobo-k2 — APPROVED** [review]

**Review by impelcrypto — APPROVED** [review]

**Pull request merged**
