### PR TITLE
added Wallet 3 and fixed detectMobile method, added missed chainName …

### PR DESCRIPTION
**Pull request by baryon**
added Wallet 3 and fixed detectMobile method and missed chainName of Astar

**Check list**
- [ ] contains breaking changes
- [X] adds new feature
- [X] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
added Wallet 3 Wallet

**Fixes**
fixed detectMobile method
fixed missed chainName of Astar

Test on Wallet 3
1. Download Wallet 3 mobile from https://wallet3.io
2. Install and Setup 
3. Open https://portal.astar.network/ from Web3 Browser of Wallet 3
4. Connect Wallet and choose Wallet 3

SCR-20220407-ivz

SCR-20220407-iur

IMG_5303 2
IMG_5304

### CODE REVIEW

**Comment by baryon** [comment]
@fiexer Hello, Please review this request. 

regards
Wallet 3 Team

**Comment by hoonsubin** [comment]
Hello @baryon, thank you for the PR. Currently, we are in the process of releasing the v2 of Astar Portal with a new layout.
Can you wait until https://github.com/AstarNetwork/astar-apps/pull/295 is merged and rebase this branch afterwords? We will review this PR carefully once we release the new Portal.

Thank you

**Comment by hoonsubin** [comment]
Please update from master

**Comment by baryon** [comment]
Updated, please review @fiexer @hoonsubin

**Comment by fiexer** [comment]
> Updated, please review @fiexer @hoonsubin

Thanks a lot! We are reviewing now.

**Review by impelcrypto — APPROVED** [review]
LGTM
@baryon 
It would be great if you could send another PR that prevents from connecting to the network again whenever the wallet is already connected to the correct chain id.  

Demo:
https://www.loom.com/share/daf1acb08c1d4596b1cc7496b0b27236

Ref:
* https://github.com/Wallet3/astar-apps/blob/main/src/hooks/c-bridge/useCbridge.ts#L382
* https://github.com/Wallet3/astar-apps/blob/main/src/hooks/useConnectWallet.ts#L97

**Comment by impelcrypto** [comment]
@baryon 
Is it possible to detect the wallet name from the Web3 instance or provider (window.ethereum)? Currently, `alert(web3.currentProvider)` returns ‘isMetaMask: true’. 

Demo:
https://www.loom.com/share/9621c113fb824cd188f292fe9bab9c32

Ref:
* https://ethereum.stackexchange.com/questions/24266/elegant-way-to-detect-current-provider-int-web3-js

image

**Comment by impelcrypto** [comment]
I will do code refactoring after this PR has been merged.

**Comment by baryon** [comment]
Metamask and its API have almost become a provider standard. Wallet3 is fully compatible with this standard. We maybe add a variable isWallet3=true later

**Review by hoonsubin — APPROVED** [review]
LGTM

**Pull request merged**
