### PR TITLE
Fix/issues staking v2

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

> Covered Issues: 2, 3, 6

2 | Tooltip: We only need those two. Please remove the ? from others.
3 | Could you make it one line when there is a space please
6 | My staking panel issues (Slack)

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Hi I'll leave this comment but if there is no time it is ok to merge, sorry my review was also slow. I'll be available in the asia Monday morning to speak when to merge. Thanks!

- Tooltip
I thought we had a kind of template? It is too long so would be great if you could fix the width of the tooltip. Also no need ? for the hero area.

- TVL: Yes USD is now fixed on the right but ASTR is now in the second line. I'd rather expect to be
100 ASTR (10USD) or
100 ASTR
(10 USD)

- My Staking Panel
I see My dApps has been removed when not connected or no staking but Unbond is still there.

<img width= 2022-10-28 at 17 24 28" src="https://user-images.githubusercontent.com/77480847/198688070-625cb01e-c7de-46f1-aa4d-a443a04ad3f2.png">
Screenshot 2022-10-28 at 17 24 46

**Comment by sirius651** [comment]
> Hi I'll leave this comment but if there is no time it is ok to merge, sorry my review was also slow. I'll be available in the asia Monday morning to speak when to merge. Thanks!
> 
> * Tooltip
>   I thought we had a kind of template? It is too long so would be great if you could fix the width of the tooltip. Also no need ? for the hero area.
> * TVL: Yes USD is now fixed on the right but ASTR is now in the second line. I'd rather expect to be
>   100 ASTR (10USD) or
>   100 ASTR
>   (10 USD)
> * My Staking Panel
>   I see My dApps has been removed when not connected or no staking but Unbond is still there.
> 

Fixed Tooltip & TVL. please check @Kahonnohak 
regarding My staking panel, there's bug in unbonding hook. need to check more. it should be separate PR

**Comment by impelcrypto** [comment]
The tooltip should be displayed whenever users hover the icon only.
https://gyazo.com/e609a1851f835578ce1afddb97b5e831

**Comment by Kahonnohak** [comment]
Thank you @sirius651 Understood that Unbonding will be a separate PR after launch so no rash. Thanks for TVL and Tooltip, looks good. Yes agree with Roy - tooltip only pop-up when people hover over the icon. We made it for other tooltips. Lets make this into Astar UI soonish.

**Comment by sirius651** [comment]
> The tooltip should be displayed whenever users hover the icon only.
> https://gyazo.com/e609a1851f835578ce1afddb97b5e831

Fixed here : https://github.com/AstarNetwork/astar-apps/pull/560/commits/564852e87035dc0bb11919758e1926363d7fd89d

**Comment by impelcrypto** [comment]
@sirius651 
I've updated styling on the tooltip area.

1. Removed `cursor pointer`
 * Before: https://gyazo.com/acac8a9faa558f6c0c8bcff4543a4afa
2. Modified background color to unify other tooltips
image

**Comment by impelcrypto** [comment]
@sirius651 @Kahonnohak 
I've adjusted line height of the cards 

=Before=

image

image


=After=
image

image

**Review by impelcrypto — APPROVED** [review]

**Pull request merged**
