### PR TITLE
fix: account and network drawer

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* keep the account information on the page while opening the account drawer
* display the 'selected account indicator' correctly
* add the closing animation for the account and network drawer
* close the account and network drawer whenever users click outside the drawer
* change the animation speed to 0.5 secs

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**Changes**

=Before=
Demo
https://www.loom.com/share/e87de5c1d0eb4e0aa55857dbca9aee8b

=After=
Demo
https://www.loom.com/share/37627993d02149ed8668c77b3af09f2b

=Before=
image

=After=
image

### CODE REVIEW

**Review by Kahonnohak — APPROVED** [review]
Thank you so much @impelcrypto 

On top of what you made, as discussed please adjust animation speed for 0.5s.

**Comment by impelcrypto** [comment]
@Kahonnohak 

> On top of what you made, as discussed please adjust animation speed for 0.5s.

Fixed.

**Review by sirius651 — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
Hi @hoonsubin @bobo-k2 
I just want to let you know that I will merge this PR tonight :)

**Pull request merged**
