### PR TITLE
Age of Chronos - dapp promotion

### PR DESCRIPTION
**Pull request by SfyLabs-HASC**
**Pull Request Summary**

> This pull request updates the _dapp_promotion.json_ file to include the latest promotional details for the **Age of Chronos** dapp.

**Check list**

- [x] contains no breaking changes
- [x] adds enhancement to the existing dapp promotion without altering its core functionality

**Adds**

- Included **Age of Chronos** in the dapp promotion section, a game that utilizes NFT 2.0 technology to offer an interactive and engaging gameplay experience.

### CODE REVIEW

**Review by bobo-k2 — CHANGES_REQUESTED** [review]
Fix image url

**Comment by SfyLabs-HASC** [comment]
fixed

**Review by gluneau — APPROVED** [review]

**Comment by Kahonnohak** [comment]
Hi I thought you are going to use this link https://twitter.com/SFY_Labs/status/1729024354489340066?s=20
And it was going to be for surprise rewards.

We have mentioned you before this is the place to help promoting your events, promotions and new features that you would like to update with users. We don't use this area to introduce your project. We will have a area that we equally introduce our ecosystem projects sometime next year.

**Comment by SfyLabs-HASC** [comment]
> Hi I thought you are going to use this link https://twitter.com/SFY_Labs/status/1729024354489340066?s=20 And it was going to be for surprise rewards.
> 
> We have mentioned you before this is the place to help promoting your events, promotions and new features that you would like to update with users. We don't use this area to introduce your project. We will have a area that we equally introduce our ecosystem projects sometime next year.

We have an active campaign FOREVER for everyone who stakes on our dapp. The post you mentioned is just one of the rewards (already sent) for stakers (November 2023). We have included the link to the main Twitter page simply because it is the channel where we will indicate all the news on rewards, winners addresses etc... it's much simpler. The post you mentioned is now outdated.

**Comment by Kahonnohak** [comment]
Understood, thank you for explaining!

**Review by Kahonnohak — APPROVED** [review]

**Pull request merged**
