### PR TITLE
Upgrade quasar to the latest version

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

I did Quasar version upgrade in effort to resolve critical security issues. Please do sanity check on staging env, also check a browser console

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by impelcrypto** [comment]
It seems something wrong with 'Balance'

=Localhost=
image
 
=Production=
image

**Comment by impelcrypto** [comment]
Getting a mysterious error message on http://localhost:8080/astar/dapp-staking/discover (open the dApp staking page directly, not clicking 'dApp Staking' tab on sidebar)
image

**Review by gluneau — APPROVED** [review]
Works fine for me

**Comment by bobo-k2** [comment]
@impelcrypto, @gluneau please re-check the PR. I fixed issues.

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
I'm not sure if this is related to this PR, but I saw the empty On-Chain Data sometimes
image

Screenshot 2023-07-26 at 7 04 22 PM

**Pull request merged**
