### PR TITLE
fix: updated bridge page styling

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: updated bridge page styling
* fix: applied background to all the pages (except dApp staking page)

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**
* fix: updated bridge page styling

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@impelcrypto hello! Where are the backgrounds?? (for dark and light theme) could you add them in the same way we have on the asset page please?

**Comment by impelcrypto** [comment]
@Kahonnohak  Isn't the same bg as the assets page?
image

**Comment by Kahonnohak** [comment]
ow seems we lost an image at some point.... Light theme still has an img. Can you add the light theme img then?  I think dark looks still ok but while is just so white...


> @Kahonnohak Isn't the same bg as the assets page? image

**Review by Kahonnohak — APPROVED** [review]
LGTM

**Review by gluneau — APPROVED** [review]

**Pull request merged**
