### PR TITLE
Remove Sio Campaign

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

Remove Sio Campaign card on dapp staking page

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

스크린샷 2023-05-17 오후 4 17 26

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you! Great work! please keep it and don't merge till Friday

**Review by Kahonnohak — APPROVED** [review]
All works great!

**Review by bobo-k2 — APPROVED** [review]

**Comment by impelcrypto** [comment]
@Kahonnohak 
You don't want to have some margin in right here, right?
image

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
@sirius651 Maybe fix the width size here a bit (make it like 100%)?

image

**Comment by sirius651** [comment]
> Good catch @impelcrypto thanks! @sirius651 please take a look.

스크린샷 2023-05-18 오후 3 21 28
스크린샷 2023-05-18 오후 3 22 41
Fixed it like this

**Comment by Kahonnohak** [comment]
Thanks! I'll let you know if we want to add an ad or we want to release as it is by tomorrow

**Comment by Kahonnohak** [comment]
@sirius651 Update,

Hi sorry, we would like to add one with Subwallet for 2 weeks from the 24th (next release). Then this will be removed.

Text:
Campaign
Subwallet
AI Art Contest with ArtZero
gradients: 49C8BA, 0B218E

Screenshot 2023-05-18 at 19 58 24

**Comment by sirius651** [comment]
> @sirius651 Update,
> 
> Hi sorry, we would like to add one with Subwallet for 2 weeks from the 24th (next release). Then this will be removed.
> 
> Text: Campaign Subwallet AI Art Contest with ArtZero gradients: 49C8BA, 0B218E
> 
> Screenshot 2023-05-18 at 19 58 24

can you create new ticket for this?

**Comment by sirius651** [comment]
스크린샷 2023-06-05 오후 3 52 18
Updated

**Comment by Kahonnohak** [comment]
Great!

**Pull request merged**
