### PR TITLE
Translation of Portal into Spanish

### PR DESCRIPTION
**Pull request by Juminstock**
Creation of a folder called 'es' inside the i18n folder containing an index.ts file with the Spanish translation of each of the words used in the Portal. In addition, I added the language to the index.ts file in the root of the i18n folder, inside the LanguageSelector.

**This pull request makes the following changes:**

**Adds**

- Add an 'es' folder and an index.ts file with the Spanish translation of the words.

**Changes**

- Modify the index.ts file in the root of the i18n folder and add the language to the LanguageSelector.

### CODE REVIEW

**Review by bobo-k2 — CHANGES_REQUESTED** [review]
Thanks a lot for the PR. General comment, use single quotes instead ". I see a lot of errors, mostly code styling (linter) ones.
Run `yarn` to install dependencies.
Run `yarn dev` to see errors.
Run `yarn lint --fix` to fix errors.

**Comment by Juminstock** [comment]
Thanks for the feedback, @bobo-k2. I have corrected the linter errors and some inconsistencies in the grammar. Now it works correctly.

**Comment by Kahonnohak** [comment]
Not sure if there is a way to make it shorter?
Screenshot 2023-12-23 at 09 52 41

**Comment by Juminstock** [comment]
> Not sure if there is a way to make it shorter? Screenshot 2023-12-23 at 09 52 41

Thanks for the observation, @Kahonnohak. I have managed to shorten several words by using synonyms, always keeping the meaning of the words. With this, aesthetically it looks better and does not break with the design.

**Review by Kahonnohak — APPROVED** [review]

**Comment by bobo-k2** [comment]
I am wandering why those 3 files below are changed and 1 is added. Since you add just translation they should be the same.
image

**Comment by Juminstock** [comment]
Except for the `.gitignore` file that I manually edited to ignore the .yarn folder, the rest of the files were automatically modified by running the commands you shared:

`yarn`
`yarn dev`
`yarn lint --fix`

If it's very problematic, I could revert the changes or create another PR. I'm awaiting your instructions, @bobo-k2.

**Comment by bobo-k2** [comment]
> Except for the `.gitignore` file that I manually edited to ignore the `.yarn` folder, the rest of the files were automatically modified by running the commands you shared:
> 
> `yarn` `yarn dev` `yarn lint --fix`
> 
> If it's very problematic, I could revert the changes or create another PR. I'm awaiting your instructions, @bobo-k2.

Hi, please create another PR. Just copy translations from this PR to the new one

**Pull request closed without merging**
