### PR TITLE
Select account - unified account display

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Clearly display unified account in the account selection modal
image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Looks good! Now we know the account a lot better:)
Could you move the balance on the right to save some space?

Screenshot 2023-10-26 at 09 19 19

**Comment by gluneau** [comment]
We may need a dark theme adjustment...

image

**Comment by bobo-k2** [comment]
> We may need a dark theme adjustment...

Thanks Greg. Fixed like this
image

**Review by impelcrypto — APPROVED** [review]
LGTM

Maybe adjust the styling to make some space between the balance and dot?
image

**Comment by bobo-k2** [comment]
> LGTM
> 
> Maybe adjust the styling to make some space between the balance and dot?

Fixed here https://github.com/AstarNetwork/astar-apps/pull/995/commits/75df611dcac5543b0af9bb3701cab2739f5dbb0c
image

**Review by gluneau — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
We could remove that dot if we don't need it - I didn't particular find it useful.

Thanks LGTM

**Review by Kahonnohak — APPROVED** [review]

**Pull request merged**
