### PR TITLE
fix testing - not found metamask window in assets-transactions-evm.spec.ts

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

fix testing - not found metamask window in assets-transactions-evm.spec.ts
from time to time, it seems not detect metamask window. so I resolved this by browsing specific metamask url as force

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by impelcrypto** [comment]
@sirius651 
Great. But why not putting 'assets-transactions-evm.spec.ts' under 'test_specs' folder?
image

**Comment by sirius651** [comment]
> @sirius651
> Great, but why not putting 'assets-transactions-evm.spec.ts' under 'test_specs' folder?

Because of chopsticks evm port issue, this test is not finally completed until it is applied

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
@sirius651 
hmm.. I got this again

**Review by bobo-k2 — APPROVED** [review]

**Comment by impelcrypto** [comment]
@sirius651 I got the same error again. @bobo-k2 Could you help check if you can reproduce the same issue on your end?

**Comment by sirius651** [comment]
> @sirius651 I got the same error again. @bobo-k2 Could you help check if you can reproduce the same issue on your end?

Hm, did you running like this as debug mode?
```
BASE_URL=\'${args[0]}\' ENDPOINT=\'${endpoint}\' npx playwright test tests/assets-transactions-evm.spec.ts --project=chromium --debug
```

**Comment by impelcrypto** [comment]
@sirius651 

> BASE_URL=\'${args[0]}\' ENDPOINT=\'${endpoint}\' npx playwright test tests/assets-transactions-evm.spec.ts --project=chromium --debug

Do you mean like this?
image

image

**Comment by sirius651** [comment]
> @sirius651
> 
> > BASE_URL='${args[0]}' ENDPOINT='${endpoint}' npx playwright test tests/assets-transactions-evm.spec.ts --project=chromium --debug
> 

I mean comment out this https://github.com/AstarNetwork/astar-apps/pull/835/files#diff-c5bcbca9d17e63c3b89bcbd6e8457972bc5b5b6840c5a28cca2d652cfc074fd3R40

then run as `yarn playwright:ci` 
it might be work for me

**Comment by impelcrypto** [comment]
> @sirius651 I got the same error again. @bobo-k2 Could you help check if you can reproduce the same issue on your end?

CC: @gluneau

**Comment by sirius651** [comment]
let me merge this

**Pull request merged**
