### PR TITLE
update theme color :: light version

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

update theme color :: light version

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

스크린샷 2023-04-20 오후 3 07 14

스크린샷 2023-04-20 오후 3 09 00

### CODE REVIEW

**Comment by impelcrypto** [comment]
Let's change [here](https://github.com/AstarNetwork/astar-apps/blob/94b56e18bef7a2342a98decc5d975e9917afbee3/src/css/quasar.variables.scss#L30) to `$gray-1`

**Comment by impelcrypto** [comment]
Maybe update the border in this input? @Kahonnohak

**Comment by Kahonnohak** [comment]
Thanks will work on review this morning

**Comment by impelcrypto** [comment]
Please update here as well (Transfer Assets and Stake page). 

* Input border has to update the color
* Remove the `border` in Information container (FAQ, Recent History, Hot Topic) 
image

**Comment by Kahonnohak** [comment]
Thanks @sirius651 

The text colours are not changed yet, please check this again

Screenshot 2023-04-20 at 10 22 22

**Comment by impelcrypto** [comment]
@Kahonnohak 

It looks like background(both header and body) is $grey-1 instead of 'white' 
image

**Comment by Kahonnohak** [comment]
ow sorry! But happy with background white we have on this staging!

**Comment by sirius651** [comment]
@impelcrypto @Kahonnohak thanks. I tried to policy on details including above feedback. please check if missing things

**Comment by impelcrypto** [comment]
@sirius651 
I think you accidentally deleted background here 
image

**Comment by impelcrypto** [comment]
@sirius651 I think you haven't updated the Stake page yet

**Comment by Kahonnohak** [comment]
@sirius651 Thanks!!
- I missed mentioning the main text colour 3c4649 -> Navy 01. 
- please also make the tag colour Navy 03 (text FFF)

This applies to all pages: Asset page, transfer page, dApp page, Project page and Staking page. I'll talk to you in the morning when I get up

**Comment by sirius651** [comment]
> @sirius651 I think you haven't updated the Stake page yet

> @sirius651 Thanks!!
> 
> * I missed mentioning the main text colour 3c4649 -> Navy 01.
> * please also make the tag colour Navy 03 (text FFF)
> 
> This applies to all pages: Asset page, transfer page, dApp page, Project page, Staking page and modals. I'll talk to you in the morning when I get up

I updated. but I'm not sure what's meaning of the tag?

**Comment by Kahonnohak** [comment]
Thanks here all tags
Screenshot 2023-04-21 at 07 46 51
Screenshot 2023-04-21 at 07 46 58
Screenshot 2023-04-21 at 07 47 11

**Comment by sirius651** [comment]
> Thanks here all tags

@Kahonnohak  Updated color on tags. anything else I had missing?

**Review by impelcrypto — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
@sirius651 

Hello! I tried to update by myself but in the end, I didn't want to mess up and wasn't sure if it was the right way to do it. (I'll talk to you in the morning)

Basically, I wanted to replace all 
1) #gray-5 should be replaced with navy-1
2) #astar-blue-dark with astar-blue

Also any other lighter gray, I believe that is  $gray-3: #9da3ae that has been used in light theme with $gray-4: #5f656f, one colour darker. 

Please check 
- Asset page
https://www.figma.com/file/s6xu63WKXosXjNCqOEknYv/Portal-V2?node-id=5484%3A99440&t=m0Hy44bD9ZgdiG3W-1

-Transfer page
https://www.figma.com/file/s6xu63WKXosXjNCqOEknYv/Portal-V2?node-id=5161%3A68199&t=m0Hy44bD9ZgdiG3W-1

-dApp Staking
https://www.figma.com/file/s6xu63WKXosXjNCqOEknYv/Portal-V2?node-id=5161%3A65587&t=m0Hy44bD9ZgdiG3W-1

- Project page
https://www.figma.com/file/s6xu63WKXosXjNCqOEknYv/Portal-V2?node-id=5161%3A64424&t=m0Hy44bD9ZgdiG3W-1

**Comment by impelcrypto** [comment]
=hover on "How to use the portal"=

Does this what you want?  It looks a bit off. @Kahonnohak 
 
image

**Comment by sirius651** [comment]
> yes thanks, @impelcrypto, I was aware but just wanted to make the big changes happen first and wanted to see if anywhere would be affected. Modals as well. Does it make sense?

I applied it as global way. can you check again?

**Comment by Kahonnohak** [comment]
Hi! Sorry for this slow reply!

Nearly there!
1) Transfer page 
- local/XCM transfer tab text -> Navy1
- Link "how to use Portal" please make the text colour -> gray1 (no need to have hover colour) -> Dark theme also is the same

2) dApp Staking top, card title -> Navy1

3) Modals, same as the transfer input, please have the border Navy as well as the title.


Screenshot 2023-04-24 at 23 25 53
Screenshot 2023-04-24 at 23 26 15
Screenshot 2023-04-24 at 23 28 05
Screenshot 2023-04-24 at 23 42 30

I double-checked and hope these are the all for the light theme.

**Comment by sirius651** [comment]
Updated colors above and common ui components in ui library (v0.0.88)

> Hi! Sorry for this slow reply!
> 
> Nearly there!
> 
> 1. Transfer page
> 
> * local/XCM transfer tab text -> Navy1
> * Link "how to use Portal" please make the text colour -> gray1 (no need to have hover colour) -> Dark theme also is the same
> 
> 2. dApp Staking top, card title -> Navy1
> 3. Modals, same as the transfer input, please have the border Navy as well as the title.
> 

> I double-checked and hope these are the all for the light theme.

Updated colors above and common ui components in ui library (v0.0.88)

**Pull request merged**
