### PR TITLE
feat: update project page styles

### PR DESCRIPTION
**Pull request by ayumitk**
**Pull Request Summary**

Updated the project page styles

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

**Project page**
1. Added the project's icon background
2. Added the animated background to the vote/stake button
3. Removed the license section from the project details
4. Vote/stake button will stick to the top of the screen when users scroll down

Screenshot 2024-01-05 at 12 00 31 PM
Screenshot 2024-01-05 at 12 02 44 PM

**Owner page**
- Added the project's icon background

Screenshot 2024-01-05 at 12 07 31 PM

**The entire app**
- Header will not stick to the top of the screen, scroll

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thanks Ayumi!

BTW rewards claim functions seems missing, can you bring it back?

@bobo-k2 please help
I still cannot see the registration button :( could you please take a look?  
Zt8cbc4J1U67fK3LysDQAudmhJybdrq7XghsTM1PDcmWvyy

**Comment by ayumitk** [comment]
Screenshot 2024-01-04 at 3 55 13 PM

@Kahonnohak 
> BTW rewards claim functions seems missing, can you bring it back?

That is because the rewards section on the assets page is for V2. So when users connect to Shibuya, it doesn't work.

@bobo-k2 @impelcrypto Could you create another rewards section file for V3?

**Comment by ayumitk** [comment]
@Kahonnohak Here are what I added to this PR. Could you review the styles and let me know if something weird.

### Project page
- Added the project's icon background
- Added the animated background to the vote/stake button
- Removed the license section from the project details
- Vote/stake button will stick to the top of the screen when users scroll down the page

### Owner page
- Added the project's icon background

### The entire app
- Header will not stick to the top of the screen, scroll

Also, I'll create another PR for the assets page styling, because this PR is getting bigger.

**Comment by Kahonnohak** [comment]
Awesome Ayumi, thank you!

1) Right side - there is some unwated space now

2) Vote hero went down quite bit
< br/>
Screenshot 2024-01-05 at 10 08 58
< br/>

3) Probably related to 2), the toggle moves its position
< br/>
Screenshot 2024-01-05 at 10 10 46
< br/>

4) I love this thank you, for the sake of align with logo, please have top padding 16 -> 24px. 
< br/>
Screenshot 2024-01-05 at 10 20 01
< br/>

5) Because the header moves now, would it be possible to bring back the header when user stops (other than project page)? Appears like 4) and disappear again when user scrolls. No need to be now tho. Will add to to-do kaizen

6) Let me experiment the gradients and mobile hero look later

**Comment by ayumitk** [comment]
@Kahonnohak Thank you for your feedback!

> 1. Right side - there is some unwated space now

Could you provide me your env, such as OS, browser, screen width and light/dark mode. I checked it on my end and can't find this white space. It looks like caused by the scroll bar background color tho🤔

> 3. Probably related to 2), the toggle moves its position

I would like to know more details about this. Do you mean the position of the toggle itself? Or when you click the toggle and it moves something position?

2,4,5 -> fixed

> 6. Because the header moves now, would it be possible to bring back the header when user stops (other than project page)? Appears like 4) and disappear again when user scrolls. No need to be now tho. Will add to to-do kaizen

Yes, I think we can do that. Let's do it at kaizen later.

**Comment by Kahonnohak** [comment]
@ayumitk thank you!

For 1) I think the scroller is hidden for dapp staking but the header still has a space for it. not a big deal if you can find easiest option to look the same across the site (I think showing the scroller is probably the way) (Brave and Chrome looks the same)
https://gyazo.com/6266430fe8201a253b541c79d048eeaf 

For 3) Weird than I though, so it is nice most times but some point it moves... you can ignore it for now.
https://gyazo.com/b836395b7483166e9378700cc92dbfb7

**Review by impelcrypto — APPROVED** [review]

**Review by Kahonnohak — APPROVED** [review]
Since this should be merged now I just left the comment and lets move to next PR

**Pull request merged**
