### PR TITLE
enhancement - update styling on dappstaking

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

- Fix shadow on dapp card
- remove right margin on dapp list in mobile view
- make a double column

(enhancement - update styling on dappstaking)

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

스크린샷 2023-04-04 오후 8 48 23

### CODE REVIEW

**Comment by impelcrypto** [comment]
Maybe add a margin-right here if it is possible?
image

**Comment by Kahonnohak** [comment]
hmmm To me it looks this wrapper is masking the box-shadow? Shadow can be changed to `0 0 8px 0px #0000001a` but the wrapper needs to include the box-shadow I think.

**Comment by Kahonnohak** [comment]
> Maybe add a margin-right here (end of the scrolling) if it is possible? image

No I don't really want a margin on the right that's what I have been asking for the hero area as well. If you add margin people think its the end of the design:(

**Comment by Kahonnohak** [comment]
Double column works well!! It's good!!

**Comment by sirius651** [comment]
> hmmm To me it looks this wrapper is masking the box-shadow? Shadow can be changed to `0 0 8px 0px #0000001a` but the wrapper needs to include the box-shadow I think.
> 

Fixed as modifying padding and shadow color like this
스크린샷 2023-04-05 오후 2 42 34

**Review by bobo-k2 — APPROVED** [review]

**Comment by Kahonnohak** [comment]
Nice so much better now thank you! two small things if you don't mind
- I would also like the margin **on the left** here as well
- Pagination is little broken

Thanks!!
スクリーンショット 2023-04-05 8 26 25
スクリーンショット 2023-04-05 8 26 46

**Comment by sirius651** [comment]
> Nice so much better now thank you! two small things if you don't mind
> 
> * I would also like the margin **on the left** here as well
> * Pagination is little broken
> 
> 
Fixed in [here](https://github.com/AstarNetwork/astar-apps/pull/731/commits/89734e03cf7472108feb49c710287dcfac3968f1)

**Review by Kahonnohak — APPROVED** [review]
Great work!!! Love it

**Pull request merged**
