### PR TITLE
Update dapp staking v3 period2 styling

### PR DESCRIPTION
**Pull request by ayumitk**
**Pull Request Summary**

- Updated dapp staking v3 period2 styling

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

- (ex: Add feature A)

**Fixes**

- (ex: Fix validation function)

**Changes**

- (ex: Change document B)

**To-dos**

> \*Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Comment by ayumitk** [comment]
@Kahonnohak I've updated the styling. Some questions are below. Could you check them?

## dApp staking page
1. Should this number be 002 as the period?
Screenshot 2024-06-08 at 11 01 52 PM

2. We might want to add the go-back button here. Otherwise, users can't change the amount.
Screenshot 2024-06-08 at 11 02 37 PM

3. Are the numbers the dApps total staked amount?
Screenshot 2024-06-08 at 11 03 51 PM

## Individual dApp staking page
4. There is no note section in the Figma, but I kept them. If you want to get rid of them, please let me know.
Screenshot 2024-06-08 at 11 22 02 PM

**Comment by bobo-k2** [comment]
@ayumitk can you also check `PeriodStats` component? Data for the component is available on Shibuya.
image

**Comment by ayumitk** [comment]
@bobo-k2 I've updated the `PeriodStats` component styling. 
Also, after merging this PR, please add the missing data below.

1. Please add the click event to navigate users to the dApp detail page. I've added `<div class="dapp-button">` for hover.
Screenshot 2024-06-10 at 7 14 05 PM

2. Please add dApps total staked amount.
Screenshot 2024-06-10 at 7 15 16 PM

**Comment by impelcrypto** [comment]
I can't see 2 and 3
image

**Comment by impelcrypto** [comment]
It looks that texts for dark theme need to be updated.
image

**Comment by ayumitk** [comment]
@impelcrypto Thank you for pointing out! I've updated the text colour for the dark theme in [bb7b5d0](https://github.com/AstarNetwork/astar-apps/pull/1309/commits/bb7b5d0417e22b9690ef09bd971452d4aa757a3a)

**Comment by impelcrypto** [comment]
Hi @ayumitk 
It's weird that I have to click _twice_ to be able to select the app here.
image

**Comment by ayumitk** [comment]
It seems the [base PR](https://github.com/AstarNetwork/astar-apps/pull/1302) has the same issue. @bobo-k2, please take a look at this as well. cc: @impelcrypto 
Screenshot 2024-06-10 at 10 53 42 PM

**Comment by bobo-k2** [comment]
> It seems the [base PR](https://github.com/AstarNetwork/astar-apps/pull/1302) has the same issue. @bobo-k2, please take a look at this as well. cc: @impelcrypto 

I don't remember having this issue before, and can't reproduce it now. @impelcrypto please share steps to reproduce.

**Comment by impelcrypto** [comment]
> I don't remember having this issue before, and can't reproduce it now. @impelcrypto please share steps to reproduce.

1. Open the dApp staking page
2. Click choose dApp
3. Defi
4. click on any dApps

**Comment by impelcrypto** [comment]
Hi @bobo-k2 @ayumitk 
It seems the error is resolved at PR: 1310.

https://astar-apps--pr1310-feat-apr-for-block-6oki12qb.web.app/astar/dapp-staking/discover

**Review by impelcrypto — APPROVED** [review]

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
LGTM too! I did not have issue! I'll merge this and share with the team!

**Review by Kahonnohak — APPROVED** [review]

**Pull request merged**
