### PR TITLE
Update onboarding modal

### PR DESCRIPTION
**Pull request by Kahonnohak**
**Pull Request Summary**

**This pull request makes the following changes:**

**Fixes**
Update some wording on onboarding modals

- (ex: Fix validation function)

Screenshot 2024-02-12 at 17 26 09
Screenshot 2024-02-12 at 17 26 04

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@bobo-k2 @impelcrypto 
Ah..I tried.. I only wanted to change those but I managed to include my try from yesterday - not sure if this is the proper way to "resolve" the conflicts. Please could you check. It has yarn lock too.

Screenshot 2024-02-12 at 17 43 25

**Review by gluneau — APPROVED** [review]
LGTM

**Review by bobo-k2 — CHANGES_REQUESTED** [review]
`yarn.lock` shouldn'b be changed if dependencies in `package.json` are not changed. Please revert the file.
If you want you can rebase the PR to `release-hotfix` and I can release it when I will enable v3 on Astar

**Comment by Kahonnohak** [comment]
Thanks bobo I'll try!! and yes will move to hotfix

**Comment by Kahonnohak** [comment]
Opened new PR and close this one

**Pull request closed without merging**
