### PR TITLE
Add dApp Twitter share button

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Share dApp on Twitter
image
image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
@Kahonnohak Should we add other descriptions like 'dApp name' on the twitter text?

**Review by sirius651 — APPROVED** [review]

**Comment by Kahonnohak** [comment]
> @Kahonnohak Should we add other descriptions like 'dApp name' on the twitter text?

For Twitter text, as we would not know the Twitter handle for the projects, they will add it by themselves.

On a different topic, I would like to change the project page URL, how hard is it? 
/dapp?dapp=0x767
↓
/"dapp name"

**Comment by Kahonnohak** [comment]
I guess I cannot see the og:img because it's stg link?
Screenshot 2023-05-18 at 08 02 15

**Comment by bobo-k2** [comment]
> 
I don't have a problem with og:image. It is displayed for me. That's weird.
Regarding project page url. It is not hard to change, but it is a good idea to rely on dapp name because we are not enforcing name uniqueness anywhere, while contract address uniqueness is guarantied. Let's discuss this.

**Comment by impelcrypto** [comment]
>  while contract address uniqueness is guarantied

Agree with @bobo-k2

**Comment by Kahonnohak** [comment]
Thanks, was long-standing question, good to be answered:) And I think the behaviour is random so that would be only me then!

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Comment by Kahonnohak** [comment]
Just to double-check, have you changed the og img to this?
OG_portal

**Comment by bobo-k2** [comment]
> Just to double-check, have you changed the og img to this?
No the OG is the same as before. See the image in the PR description

**Comment by Kahonnohak** [comment]
Okay for now, it's strange that Twitter seems to keep the cache as well - we changed the description long time ago but I can still see the old one. That would be a separate ticket since we would probably change the description again soon. Thanks for clarifying!

**Pull request merged**
