### PR TITLE
feat: load the dApps data in advance (on the Asset page)

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: modified displaying `Eras` on the My Rewards panel
  * avoid displaying loading skeleton too much  
* fix: open the 'Select wallet' modal on the Stake page if users haven't connected wallet or connected to EVM wallets

* fix: added loading animation whenever the portal is fetching dApps data
* feat:  load the dApps data in advance (on the Asset page), so that users can access to dApp staging page smoothly

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Fixes**

* fix: modified displaying Eras on the My Rewards panel
  * avoid displaying loading skeleton too much  
  
=Before=
https://www.loom.com/share/40a3fc35c2f7466a8a1b168aa587844a

=After=
https://www.loom.com/share/5f63ffa0e09c4a2da52a2e410ca6e07a

* fix: open the 'Select wallet' modal on the Stake page if users haven't connected wallet or connected to EVM wallets

image

**Changes**
- (ex: Change document B)

**To-dos**
> *Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Hi! 

I thought it would be good to have the 'Your Rewards' panel for people who are not connected. So first-time users can expect what it is easily?

And second, thanks but can we say 'connect' instead of disabling the button?

Thank you!

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
@Kahonnohak Modified, please take a look again.

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Pull request merged**
