### PR TITLE
Bridge and assets page styling fixes

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

image

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
sorry @bobo-k2 
Dark theme doesn't have anything. Could you also align with the asset page box please

Screenshot 2023-10-23 at 10 45 34

**Comment by Kahonnohak** [comment]
@bobo-k2 aw sorry miscommunication

I wanted to keep the current grey border as default and want to have the blue border for hover (dark) 
and just add a hover blue for the light theme.

Does it make sense?? Let me know if I made you confused!

**Comment by bobo-k2** [comment]
> @bobo-k2 aw sorry miscommunication
> 
> I wanted to keep the current grey border as default and want to have the blue border for hover (dark) and just add a hover blue for the light theme.
> 
> Does it make sense?? Let me know if I made you confused!

I understood that you want to have shadow around buttons on the bridge page. Let me fix the styling

**Review by gluneau — APPROVED** [review]
LGTM

**Review by Kahonnohak — APPROVED** [review]
Thank you!

**Pull request merged**
