### PR TITLE
feat:Support for BNC and vKSM assets(shiden)

### PR DESCRIPTION
**Pull request by hqwangningbo**

### CODE REVIEW

**Comment by hqwangningbo** [comment]
https://astar.test.liebi.com/#/shiden/assets

**Comment by impelcrypto** [comment]
Hi @hqwangningbo
Thank you for your contribution. Kindly submit required subscan links again. Thanks.
https://docs.astar.network/docs/xcm/integration/add-to-portal#requirements-for-creating-a-pr

**Comment by impelcrypto** [comment]
Also, please help send some tokens to 5H6DC1YjyD531FiGxPCpWY3WNJrp5kQ35xHm6wibKuFvWzKW for testing.

CC: @bobo-k2  @Kahonnohak

**Comment by hqwangningbo** [comment]
1. BNC
https://bifrost-kusama.subscan.io/xcm_message/kusama-542ad5d19abd98b1653937e19a8deda1b5e21ded
2. vKSM
https://bifrost-kusama.subscan.io/xcm_message/kusama-0d0f6b7dc4cba23de9e95dd16678261589f1b7e7
3. SDN
https://bifrost-kusama.subscan.io/xcm_message/kusama-2b89b2c1fb242c65f6d00b8d63ff1f524acbe770

**Comment by hqwangningbo** [comment]
> Also, please help send some tokens to 5H6DC1YjyD531FiGxPCpWY3WNJrp5kQ35xHm6wibKuFvWzKW for testing.
> 
> CC: @bobo-k2 @Kahonnohak

@impelcrypto Related tokens have been sent, please check

**Comment by Kahonnohak** [comment]
@impelcrypto Send them to me so I can take over the test. 5C7jzpzLw5jEejupKCpKfu6dwcdG9M1Jhgz9htqPGx9GwXbN

**Comment by impelcrypto** [comment]
Thanks, @hqwangningbo. Please also send some tokens to @Kahonnohak as well.

**Comment by hqwangningbo** [comment]
> 5C7jzpzLw5jEejupKCpKfu6dwcdG9M1Jhgz9htqPGx9GwXbN

Done

**Comment by Kahonnohak** [comment]
> > 5C7jzpzLw5jEejupKCpKfu6dwcdG9M1Jhgz9htqPGx9GwXbN
> 
> Done

Thanks, Both Astar Native and Astar EVM, Deposit/ withdrawal were all successful!

**Review by Kahonnohak — APPROVED** [review]
LGTM

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
