### PR TITLE
feat: updated theme color

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: updated theme color

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Release notes:**

* feat: updated dark theme

**This pull request makes the following changes:**

**Changes**

* feat: updated dark theme
image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@impelcrypto the header has a problem. We had a nice effect that picks up the bottom colour with blur and that is now gone. Could you take a look and bring this back please? And actually if it has more opacity that would be even better.
Screenshot 2023-04-20 at 09 45 11

**Comment by impelcrypto** [comment]
@Kahonnohak 
Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/741/commits/dcd08066d3084d9fd6f5df75cfd0374e76c30eef) commit (and increased opacity level).

CC: @sirius651 

image

**Comment by Kahonnohak** [comment]
Nice thanks, I like the sidebar gradients too.

**Comment by Kahonnohak** [comment]
Another things - I'm ok with the dApp Staking hero have padding below the header but could you please have the same radius and make more space please?

I tried and find here to adjust, looks like reasonable to have 12-> 24px

Screenshot 2023-04-20 at 11 54 02

**Comment by impelcrypto** [comment]
@Kahonnohak updated.

**Comment by Kahonnohak** [comment]
Sorry I missed a couple of areas.

Please take a look at Project page, dropdown and modals.

Screenshot 2023-04-20 at 21 21 25
Screenshot 2023-04-20 at 21 22 41
. 

Screenshot 2023-04-20 at 21 14 33

**Comment by impelcrypto** [comment]
@Kahonnohak 
> Please take a look at Project page, dropdown and modals. I would like the tag with Navy03, Thanks!

Please update all these in Figma, not in this PR, so that we can refer to the updated master design later as well.

**Comment by Kahonnohak** [comment]
Sorry forgot to update!
https://www.figma.com/file/s6xu63WKXosXjNCqOEknYv/Portal-V2?node-id=5161%3A64182&t=m0Hy44bD9ZgdiG3W-1

**Comment by impelcrypto** [comment]
@Kahonnohak Updated, please check it out.

**Comment by Kahonnohak** [comment]
Hi! 

Thanks! I went through it again and I got a few to share. Please take a look.

1) Asset page
- Could you change this blue -> astar-blue please.
- The video link - Mentioned in the light theme but please change the colour of the text to gray01 and no need hover.
Screenshot 2023-04-24 at 23 50 21

2)dApp Staking top
- Please change the tag colour and the border below to Navy03
- Title border -> rainbow
- Please have 80px paddings between contents (it looked tight, project page as well)
Screenshot 2023-04-25 at 00 03 45

3)Project page
- Builders background colour -> Navy02 please
Screenshot 2023-04-25 at 00 00 44

4) Modals
- Please make the background #080f2e80

5) Mobile Header wasn't applied yet, sorry didn't check til now.
Screenshot 2023-04-24 at 23 45 48

**Comment by Kahonnohak** [comment]
Thanks! Some places are mixed up now
1) Transfer page
- on Dark theme I cannot see the texts on the tab, this should be #F7F7F8
- Did not see the change but the link text for both Dark and Light, I think #F7F7F8 is softer (no hover effect needed)

2) Modal
- on Dark theme it lost the border colour and the background to be 080f2e80 please?

3) Mobile Header
- Can we have the same mobile header on the light theme too?

4) Mobile project page
- I spotted, please make it Navy02
Screenshot 2023-04-25 at 12 25 54


I think that is all!!!

**Comment by Kahonnohak** [comment]
Two points!
- [both dark and light] The link text "HOW TO USE PORTAL -> #F7F7F8
- [Dark theme] Background of the modal -> #080f2e80

Sorry if it was not clear before.

Screenshot 2023-04-26 at 12 31 13

Screenshot 2023-04-26 at 12 26 07

**Review by Kahonnohak — APPROVED** [review]
Great work!

**Pull request merged**
