### PR TITLE
Add subwallet campaign

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

Add subwallet campaign

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you! Then lets do it. We already be supported by Subwallet so no matter if it is not listed or not.

subwallet 1

**Comment by Kahonnohak** [comment]
Also please like to here: https://docs.artzero.io/artzero-articles/8-5-23-astar-x-subwallet-x-artzero-ai-art-contest

**Comment by sirius651** [comment]
@Kahonnohak Updated. please check

**Comment by impelcrypto** [comment]
Could you add an e2e test?

**Review by impelcrypto — APPROVED** [review]

**Pull request merged**
