### PR TITLE
fix: display translated messages on the toast

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: display translated messages on the toast
* feat: display subacan links on the toast after sending XCM transactions 
* todo: sending transactions via light client 
  * Somehow we rollbacked `useTokenTransfer.ts` to old version after light client integration, so I've updated the file. Sending tokens via light client still doesn't work yet, but this is an [another issue](https://github.com/smol-dot/smoldot/issues/416) and we can fix it later.    

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

* feat: display subacan links after sending XCM transactions 
image

**Fixes**

fix: display translated messages on the toast
  * added translated `successMessage` as a parameter in service files in V2 structure

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @bobo-k2 

> Somehow we rollbacked useTokenTransfer.ts to old version after light client integration

I found that we rollbacked in this PR. Could you share with me what was the issue? So I can try to reproduce in this branch.
https://github.com/AstarNetwork/astar-apps/pull/679

**Comment by impelcrypto** [comment]
CC: @Kahonnohak

**Comment by bobo-k2** [comment]
> #679

Just paste the PR url in Slack, it will lead you to conversation about the issue.

**Comment by impelcrypto** [comment]
@bobo-k2 fixed the issue mentioned at https://github.com/AstarNetwork/astar-apps/pull/679 at [this](https://github.com/AstarNetwork/astar-apps/pull/738/commits/0b98de12ad79c065f83a2db3851031f9a6444402) commit

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
