### PR TITLE
styles: added stake page

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**
* styling: added stake page
  * note: I haven't implemented staking logic yet. This PR is for page styling only.
  * path: /dapp-staking/stake?dapp=${dappAddress}
    * e.g: https://astar-apps--pr519-styling-stake-page-3ouc29dm.web.app/#/astar/dapp-staking/stake?dapp=0xa602d021da61ec4cc44dedbd4e3090a05c97a435

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

image

image

* Added 'Stake Now' button (temporary) 
image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Hi sorry it is my understanding.

1) Please remove the message completely.
`After moving your funds, you will have 10 days of cooldown period in the dApp before you can make transfers/unstake`

2) Please change the layout to align the contents.
Screenshot 2022-09-26 at 12 45 51

3) FAQ
https://docs.google.com/spreadsheets/d/1ZEQi0yWMfB-ipmOrMcwevoWlPU_3Nzk-EVH5FMK34NY/edit#gid=1863197637&range=21:21

Thanks!

**Comment by impelcrypto** [comment]
@Kahonnohak Pushed, please take a look againt

**Comment by Kahonnohak** [comment]
Thank you! 

Sorry...
1) forgot to mention but could you change the button and use the one in Astar UI please!
2) Mistake, please use this link for "What is dApps Staking?" https://docs.astar.network/docs/dapp-staking/

Otherwise all good!

**Comment by impelcrypto** [comment]
@Kahonnohak updated

**Comment by Kahonnohak** [comment]
All look good thanks!

**Pull request merged**
