### PR TITLE
Faucet bot link

### PR DESCRIPTION
**Pull request by niklabh**
**Pull Request Summary**

Fix broken link for faucet bot.

> Describe what changes this pull request makes to the repository

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
- (ex: Add feature A)

**Fixes**
- (ex: Fix validation function)

**Changes**
- (ex: Change document B)

**To-dos**
> *Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
@niklabh I got this error on Shibuya
image

**Comment by impelcrypto** [comment]
@niklabh I've sent an invitation to your email address to the Google reCAPTCHA

**Comment by impelcrypto** [comment]
@niklabh Is [this](https://github.com/AstarNetwork/astar-apps/blob/24d9b9b6ad8a543658bb9b767b8cc84e6fbb999a/src/hooks/useFaucet.ts#L55) endpoint correct?

https://us-central1-facuet-bot.cloudfunctions.net/app/shiden/drip/?destination=${walletAddress}

**Review by hoonsubin — APPROVED** [review]

**Comment by impelcrypto** [comment]
Hi @hoonsubin there are still open issues as described above

**Comment by hoonsubin** [comment]
oh, your comment was not visible on my side for some reason. Sorry

**Comment by hoonsubin** [comment]
@niklabh please open another PR with the fixes. This was my bad

**Comment by niklabh** [comment]
Link will remain same. Fixing in faucet bot repo

**Comment by niklabh** [comment]
Link should change as heroku was deleted.

**Pull request merged**
