### PR TITLE
Fix issue : #380

### LINKED ISSUE #380: [Bug report] Wallet connection is not being recognized after switching between networks
**Describe the bug**
> A clear and concise description of what the bug is.

After testing https://github.com/AstarNetwork/astar-apps/pull/377 in the staging environment, my Talisman wallet connection is not being shown even though the page can read my account.

**To Reproduce**

1. Open the portal page
2. Switch the networks
3. After some point, the wallet connection disappears

**Expected behavior**
> A clear and concise description of what you expected to happen.

The wallet connection should always be established.
Furthermore, when you enter the portal page for the first time with a polkadot wallet, the page will ask for you to allow the page to access the wallet before the user even presses connect. This should not be the case and the page should only request access to the extension when the user clicks connect.

**Screenshots**
> If applicable, add screenshots to help explain your problem.

https://user-images.githubusercontent.com/40356749/166420597-97fad163-bfd8-4e6f-b161-1cbe7270f0a1.mp4

**Desktop (please complete the following information)**
 - OS: Windows
 - Browser: Chrome
 - Version: Latest
 - Wallet: Talisman

**Smartphone (please complete the following information)**

**Additional information**
> Add any other information about the problem here.

There were no console error logs

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

Fix #380 

> Describe what changes this pull request makes to the repository

``
Furthermore, when you enter the portal page for the first time with a polkadot wallet, the page will ask for you to allow the page to access the wallet before the user even presses connect. This should not be the case and the page should only request access to the extension when the user clicks connect.
``

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
스크린샷 2022-05-06 오전 11 29 20
(when user try to connect at first)

There seems to be no handler to check whether authorized or not. So, record the status for the first time access to localstorage , and if there is no value, skip what is in the boot file. (also connect network button only visible) Then when the user clicks the connect button to connect to the network, the page is reloaded and run the process in the boot as it is now.

### CODE REVIEW

**Comment by sirius651** [comment]
This PR is for first-time access users whose related information does not remain in localstorage. if there's any other exception here (such as the Wallet), please let me know.

**Comment by hoonsubin** [comment]
I am getting an error where when the page prompts the extension to connect and I don't do anything for 15 seconds, the page will automatically get back to the wallet selection drawer and I cannot connect my accounts. I'm using Talisman

**Comment by sirius651** [comment]
> I am getting an error where when the page prompts the extension to connect and I don't do anything for 15 seconds, the page will automatically get back to the wallet selection drawer and I cannot connect my accounts. I'm using Talisman

can you record the screen or give me more detail description how to reproduce that? I'm not encountered that case or others can reproduce this? @impelcrypto @bobo-k2 @Kahonnohak

**Comment by hoonsubin** [comment]
> > I am getting an error where when the page prompts the extension to connect and I don't do anything for 15 seconds, the page will automatically get back to the wallet selection drawer and I cannot connect my accounts. I'm using Talisman
> 
> can you record the screen or give me more detail description how to reproduce that? I'm not encountered that case or others can reproduce this? @impelcrypto @bobo-k2 @Kahonnohak

Strange, I cannot seems to reproduce it anymore (tried it from a new PC too).

https://user-images.githubusercontent.com/40356749/167245978-45c1f47f-5430-46ad-9af9-14fbdddd46ef.mov

In any case, would it be possible to connect to the network and open the wallet drawer before asking the wallet to connect?
I would like the wallet to ask for permission AFTER the user selects a wallet to connect.

**Comment by Kahonnohak** [comment]
So when I wasn't connected, I didn't get the wallet modal drawer at all and just the network connect button was there. Somehow this happens Chrome and Firefox and Brave seems good.

Chrome and Firefox:
スクリーンショット 2022-05-08 15 50 07

Brave:
スクリーンショット 2022-05-08 16 08 49


The current expected behaviour is to show the wallet drawer in default and Network should be connected to Astar.

**Comment by sirius651** [comment]
I separated the connection network part of connectApi and the account load part of extension into separate hooks. If the selected account is linked, it is automatically called or the hook is called directly. it seems works on my end when I double checked that. please verify on this @hoonsubin @Kahonnohak

**Comment by Kahonnohak** [comment]
Chrome and Brave are now working as expected. Firefox looks add - the button says not connected to Network, however, the balance on Astar will show up once you connect to a wallet. I'm checking on Mac. Do you need me to check on Windows? (I still have not got an Android yet...)

Firefox-
スクリーンショット 2022-05-09 15 09 42

**Comment by sirius651** [comment]
> Chrome and Brave are now working as expected. Firefox looks odd - the button says not connected to Network, however, the balance on Astar will show up once you connect to a wallet. I'm checking on Mac. Do you need me to check on Windows? (I still have not got an Android yet...)
> 
> Firefox- スクリーンショット 2022-05-09 15 09 42

Unfortunately, I can't reproduce it at Firefox (Mac). Is this only the distributed url for this ticket? Or how about an official portal? @Kahonnohak

**Comment by Kahonnohak** [comment]
That’s the thing🧐 - production works fine as expected.

**Pull request merged**
