### PR TITLE
set default connect with astar network

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

for first user, set default selectEndpointData in local storage, so they can see Astar Network on button as default
스크린샷 2022-05-18 오후 11 52 38

### CODE REVIEW

**Review by hoonsubin — APPROVED** [review]

**Comment by impelcrypto** [comment]
Is it possible to display the accounts menu whenever users select the wallet for first time (00:14 in the video)? 
https://www.loom.com/share/02020fd984b14bfcae09ead5aee0b307

**Comment by Kahonnohak** [comment]
@impelcrypto I actually come across this issue regularly. I cannot tell when it displays without accounts but it does happen. Would be great to find a solution for this.

**Comment by impelcrypto** [comment]
@sirius651 

I'm not sure if this can help. Perhaps change the [port number](https://github.com/AstarNetwork/astar-apps/blob/main/quasar.conf.js#L94) while debugging? So to your wallet it seems like this is the first time visiting so you can test as a first time visitor.

**Comment by sirius651** [comment]
> @sirius651
> 
> I'm not sure if this can help. Perhaps change the [port number](https://github.com/AstarNetwork/astar-apps/blob/main/quasar.conf.js#L94) while debugging? So to your wallet it seems like this is the first time visiting so you can test as a first time visitor.

I think resolved above issue by refetching loadAccount for first access. please check @impelcrypto @Kahonnohak

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
> I think resolved above issue by refetching loadAccount for first access. please check @impelcrypto @Kahonnohak

LGTM
Demo: https://www.loom.com/share/ccebd934027c4475a892b72dc75282dd

**Comment by Kahonnohak** [comment]
Brilliant! Thank you!

**Review by Kahonnohak — APPROVED** [review]

**Pull request merged**
