### PR TITLE
hide blog section

### PR DESCRIPTION
**Pull request by gtg7784**
**Pull Request Summary**

> Hiding the blog section in the mobile header

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

- Hide the blog section in the mobile header

### CODE REVIEW

**Review by bobo-k2 — APPROVED** [review]
LGTM, but please check with @Kahonnohak if anything needs to be added to mobile navigation

**Review by impelcrypto — APPROVED** [review]

**Comment by Kahonnohak** [comment]
Thanks,

I understood that the content on mobile navi is not linked to the same content on desktop.
- Please add Forum
- Please change the Startale logo

Yes remove the blog for now thanks!!

**Comment by gtg7784** [comment]
> Thanks,
> 
> I understood that the content on mobile navi is not linked to the same content on desktop.
> 
> * Please add Forum
> * Please change the Startale logo
> 
> Yes remove the blog for now thanks!!

For the startale logo, we will release it by next release cycle (next week)
I'll add Forum soon, thank you!

**Comment by gtg7784** [comment]
> > Thanks,
> > I understood that the content on mobile navi is not linked to the same content on desktop.
> > 
> > * Please add Forum
> > * Please change the Startale logo
> > 
> > Yes remove the blog for now thanks!!
> 
> For the startale logo, we will release it by next release cycle (next week) I'll add Forum soon, thank you!

Resolved with [2546ad1](https://github.com/AstarNetwork/astar-apps/pull/1399/commits/2546ad123a34ac9fa1ab7bac4a197dfddbbd3115)

@Kahonnohak can you please take a look again? thank you!

**Review by Kahonnohak — APPROVED** [review]

**Pull request merged**
