### PR TITLE
Add Hydration to XCM

### PR DESCRIPTION
**Pull request by green-jay**
**Description:**
Adds HDX + ASTR to XCM transfers between Hydration <> Astar

**Preview:**
https://spa-4bqy1qnsk-greenees-projects.vercel.app/

**Transfers tested:**
https://astar.subscan.io/xcm_message/polkadot-ba2f23b71f95936751b70718b4975d2d74fc4871
https://astar.subscan.io/xcm_message/polkadot-cd6d77e8cefd00d790a153664a3b6e31460c45a7
https://astar.subscan.io/xcm_message/polkadot-0aea895899ae7227b3d3c02d82d3eab7fa45fe8d
https://astar.subscan.io/xcm_message/polkadot-1e5ccb2dc4f90448859d047b953398388b58e4fc

### CODE REVIEW

**Comment by gtg7784** [comment]
Hi @green-jay, Thank you for your contribution!
Can you please send me some HDX for testing?
this is my address! thanks :)
`5CQ3neVsWFigPALbdfJCrJWaVZDboB3W7u93LQhggETGQEcy`

**Comment by green-jay** [comment]
> Hi @green-jay, Thank you for your contribution! Can you please send me some HDX for testing? this is my address! thanks :) `5CQ3neVsWFigPALbdfJCrJWaVZDboB3W7u93LQhggETGQEcy`

Sent, btw i recommend you to try our Hydration app ui for swapping!

**Comment by gtg7784** [comment]
> > Hi @green-jay, Thank you for your contribution! Can you please send me some HDX for testing? this is my address! thanks :) `5CQ3neVsWFigPALbdfJCrJWaVZDboB3W7u93LQhggETGQEcy`
> 
> Sent, btw i recommend you to try our Hydration app ui for swapping!

If I need more, I'll try to swap in your app ui!

btw, I cannot access to vercel link above. Can you please check it?
image

**Comment by green-jay** [comment]
> > > Hi @green-jay, Thank you for your contribution! Can you please send me some HDX for testing? this is my address! thanks :) `5CQ3neVsWFigPALbdfJCrJWaVZDboB3W7u93LQhggETGQEcy`
> > 
> > 
> > Sent, btw i recommend you to try our Hydration app ui for swapping!
> 
> If I need more, I'll try to swap in your app ui!
> 
> btw, I cannot access to vercel link above. Can you please check it? image

Can you try now please? updated link: https://spa-4bqy1qnsk-greenees-projects.vercel.app/

**Comment by impelcrypto** [comment]
Hi @green-jay 
Please also send some token to `5H6DC1YjyD531FiGxPCpWY3WNJrp5kQ35xHm6wibKuFvWzKW`, I'll test it out. Thanks.

**Comment by green-jay** [comment]
> Hi @green-jay Please also send some token to `5H6DC1YjyD531FiGxPCpWY3WNJrp5kQ35xHm6wibKuFvWzKW`, I'll test it out. Thanks.

sent

**Comment by gtg7784** [comment]
> > > > Hi @green-jay, Thank you for your contribution! Can you please send me some HDX for testing? this is my address! thanks :) `5CQ3neVsWFigPALbdfJCrJWaVZDboB3W7u93LQhggETGQEcy`
> > > 
> > > 
> > > Sent, btw i recommend you to try our Hydration app ui for swapping!
> > 
> > 
> > If I need more, I'll try to swap in your app ui!
> > btw, I cannot access to vercel link above. Can you please check it? image
> 
> Can you try now please? updated link: https://spa-4bqy1qnsk-greenees-projects.vercel.app/

스크린샷 2024-06-14 오후 6 34 39

This is not work too 😢

**Comment by green-jay** [comment]
> > > > > Hi @green-jay, Thank you for your contribution! Can you please send me some HDX for testing? this is my address! thanks :) `5CQ3neVsWFigPALbdfJCrJWaVZDboB3W7u93LQhggETGQEcy`
> > > > 
> > > > 
> > > > Sent, btw i recommend you to try our Hydration app ui for swapping!
> > > 
> > > 
> > > If I need more, I'll try to swap in your app ui!
> > > btw, I cannot access to vercel link above. Can you please check it? image
> > 
> > 
> > Can you try now please? updated link: https://spa-4bqy1qnsk-greenees-projects.vercel.app/
> 
> 스크린샷 2024-06-14 오후 6 34 39
> This is not work too 😢

i'm not sure if there is anything more i can do, maybe you can build it locally?

**Review by impelcrypto — APPROVED** [review]
LGTM

**Review by gtg7784 — APPROVED** [review]
LGTM

**Pull request merged**
