### PR TITLE
feat: updates Polkadot.js packages

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: updates Polkadot.js packages

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

* feat: updates Polkadot.js packages

**To-dos**
* [Resolved] Resolve unknown errors
  * it seems removing [this](https://github.com/AstarNetwork/astar-apps/blob/main/src/store/dapp-staking/actions.ts#L107) line helps resolving one of errors, but I don't think this is the root cause. 

* Resolve `test` (yarn test)
    
image

image

### CODE REVIEW

**Comment by sirius651** [comment]
when I debug this, regarding `@polkadot/x-textdecoder` issue, that comes from `import { BN } from '@polkadot/util';`. maybe we can resolve by replacing BN from alternatives?

**Comment by impelcrypto** [comment]
> when I debug this, regarding @polkadot/x-textdecoder issue, that comes from import { BN } from '@polkadot/util';. maybe we can resolve by replacing BN from alternatives?

@sirius651 I think that Polkadot.js packages require importing BN from '@polkadot/util' package (as @bobo-k2 explained in slack) but you can try.

**Comment by sirius651** [comment]
> > when I debug this, regarding @polkadot/x-textdecoder issue, that comes from import { BN } from '@polkadot/util';. maybe we can resolve by replacing BN from alternatives?
> 
> @sirius651 I think that Polkadot.js packages require importing BN from '@polkadot/util' package (as @bobo-k2 explained in slack) but you can try.

`import { BN } from '@polkadot/util'`
unfortunately, there are so many places this code can be utilized on all services, repositories. I wanted to get idea from @bobo-k2

**Review by sirius651 — APPROVED** [review]

**Review by gluneau — APPROVED** [review]
The tests run well, the code looks good.

**Pull request merged**
