### PR TITLE
feat: new network and wallet modal

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* added new network and wallet modal

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

image

image

image

**Todos**
Check if E2E test fails

### CODE REVIEW

**Comment by ayumitk** [comment]
When the screen loads, the Network and Wallet tabs work without issues.

However, after pressing the Wallet button in the header and opening the Wallet tab, I cannot switch back to the Network tab. (or this might not be the expected user behaviour tho)
https://www.loom.com/share/46af00d7148c4da59a78f88cb56db755?sid=43156aec-1ea2-45b9-b323-0ca3679f75e7

**Comment by impelcrypto** [comment]
@ayumitk Thanks, I'll take a look

**Comment by impelcrypto** [comment]
@ayumitk Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/1123/commits/edf34b34bfe653573611106b20af444117680fea) commit.

**Review by ayumitk — APPROVED** [review]

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
Hi thanks @impelcrypto , few points please

1) the space between the tab ->16px
2) Font weight 700px when selected
Screenshot 2024-01-24 at 19 32 21

3) Side margin 40px (desktop)

Screenshot 2024-01-24 at 19 33 14

4) the gap between the content and the banner 40px but Please just hide the banner for now
Screenshot 2024-01-24 at 19 33 29

5) I would like to have one button saying "Next", no need two buttons?
Screenshot 2024-01-24 at 19 34 05

**Comment by Kahonnohak** [comment]
Just found that disconnect doesn't work, please take a look
https://www.loom.com/share/042816f8db61483da29c71128b48872d?sid=237766f1-7671-42ad-8548-045018c939e5

**Comment by impelcrypto** [comment]
@Kahonnohak Updated.

* Before hiding the ads section
image

* After hiding the ads section
image

**Review by gluneau — APPROVED** [review]

**Review by Kahonnohak — APPROVED** [review]
Great work!

**Pull request merged**
