### PR TITLE
Restake rewards

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Added an optional feature to restake user rewards. Reward will be proportionally staked on dApp user is currently staking on. 

There are two use cases
- First one when staking to dApps. Go through staking wizard components. Restake modal is the last step and it will be shown in case you have rewards to claim.
- Second one when claiming rewards

Short tutorial https://www.loom.com/share/b8bef5757c164140a3229187e11d214d

image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]

**Comment by impelcrypto** [comment]
@bobo-k2 How can I open the modal?

**Comment by bobo-k2** [comment]
> @bobo-k2 How can I open the modal?

I am sorry I didn't describe that. You need to go through staking wizard. This is the last step in case you have rewards to claim

**Comment by impelcrypto** [comment]
@bobo-k2 
Like this? Could you help share the record?
https://www.loom.com/share/c124d3eb022849938deb104093ed4be8

**Comment by bobo-k2** [comment]
> @bobo-k2 Like this? Could you help share the record? https://www.loom.com/share/c124d3eb022849938deb104093ed4be8

Added recording to the PR desscription

**Comment by impelcrypto** [comment]
@bobo-k2 Thanks, LGTM

**Review by gtg7784 — APPROVED** [review]
LGTM

**Pull request merged**
