### PR TITLE
Polkadot version upgrade

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Upgraded Polkadot js version in order to solve an issue with Claim feature on the portal. Most likely the root cause of the error is weigh type change from u64 to struct Weight

image

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**
- Polkadot version upgrade
- use BN exported by Polkadot js

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]
Great work!

**Review by hoonsubin — APPROVED** [review]
LGTM!

**Review by sirius651 — APPROVED** [review]

**Comment by hoonsubin** [comment]
@bobo-k2 is this PR okay to merge?

**Comment by bobo-k2** [comment]
> @bobo-k2 is this PR okay to merge?

Before we merge the PR I want to be sure that nothing is broken. There was an error in dapp staking because polkadot upgrade which is fixed. I asked Roy to do sanity check on Assets page including XCM but he is OOO. Can you do me a favour and try few transactions just to make sure that nothing is broken?

**Comment by hoonsubin** [comment]
> > @bobo-k2 is this PR okay to merge?
> 
> Before we merge the PR I want to be sure that nothing is broken. There was an error in dapp staking because polkadot upgrade which is fixed. I asked Roy to do sanity check on Assets page including XCM but he is OOO. Can you do me a favour and try few transactions just to make sure that nothing is broken?

Screenshot from 2022-10-24 11-33-40

I don't know if it's because of the package update, but the wallet fails to sign transactions on Polkadot RPC.

**Comment by bobo-k2** [comment]
@impelcrypto can you please help with the issue above?

**Comment by impelcrypto** [comment]
@bobo-k2 @hoonsubin 

> I don't know if it's because of the package update, but the wallet fails to sign transactions on Polkadot RPC.

It works on my end. I've tested on both Chrome and Firefox.

Wallet: Talisman (V.1.9.0)
Endpoint: Astar, OnFinality
Browser: Firefox, Chrome
OS: Mac
XCM transaction: Deposit Dot to Astar network

image

image

**Review by hoonsubin — APPROVED** [review]

**Pull request merged**
