### PR TITLE
[SubWallet] Enable Mobile version

### PR DESCRIPTION
**Pull request by S2kael**
**Pull Request Summary**

This is the pull request I have created for the integration of our SubWallet mobile into the Astar portal. Please merge.

## Change
- Update wallet config

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @S2kael 
Thank you for your contribution. Kindly please take a look at [this](https://docs.astar.network/docs/builder-guides/Integration%20and%20Toolings/add-wallets-to-portal#requirements-for-creating-a-pr) and submit the required links.

**Comment by NamPhamc99** [comment]
Hello @impelcrypto, we are preparing the necessary information for the integration here https://github.com/Koniverse/SubWallet-Mobile/issues/297. I'm wondering if we can pass the PR without having to test out every case mentioned in the doc ?

To be specific, we are having trouble getting some tokens to test out every case. We see that the Portal only requests signature from the wallet to submit transaction so technically we don't need to test with every single type of token. 

SubWallet Mobile works just like SubWallet extension so we are sure it doesn't bring any strange behavior to the Portal. SubWallet extension has been working well on Astar Portal for over a year so i think it would be fine. Plus, i see that the there was only 1 commit and it was just about changing some configurations.

**Comment by impelcrypto** [comment]
> To be specific, we are having trouble getting some tokens to test out every case.

Which tokens you are having trouble for testing? I can't allow you to merge this PR without testing. Also please deploy this this branch to somewhere like [Vercel](https://docs.astar.network/docs/builder-guides/Integration%20and%20Toolings/deploy-astar-portal), so that our team can test the functions. 

CC @togamamora @fiexer @Kahonnohak

**Comment by NamPhamc99** [comment]
Here are the resources of the testing that we've done
https://drive.google.com/file/d/1nJmfmMxd6E9RPHj2D7yFdcXXASVZ_Nt6/view
For more detail of the testing, see this issue here
https://github.com/Koniverse/SubWallet-Mobile/issues/297

We have not found ways to test out these cases (mainly because we currently don't have the corresponding tokens):
Substrate wallet:
- XCM transfers: deposit & withdrawal
EVM wallet:
- ERC20 token transfer
- XCM transfer
- Withdrawal

Do we have to try out every single case ? Since some cases are similar and it would take us a while to get tokens

cc @impelcrypto

**Comment by impelcrypto** [comment]
Thank you, I'll test it out tomorrow. 
1. Can I assume that the branch is working fine on Android as well?
2. Could you deploy this branch to somewhere like Vercel as I requested above? so that our team can test it out easily.

**Comment by NamPhamc99** [comment]
1. Yes, everything is working well on Android. Our testing team tested on both Android/iOS
2. Yes we are working on it, we will submit a Vercel deployment soon

Thank you

**Comment by S2kael** [comment]
Here is the deployment link: [Vercel](https://astar-portal-wheat.vercel.app/)

**Comment by impelcrypto** [comment]
Hi @NamPhamc99 

It looks like the `Approve request` won't be closed after I tap either `Reject` or `Approve`.

OS: Android (Oneplus A3000)
App version: 0.2.3

image

image

**Comment by impelcrypto** [comment]
It looks like `Approve request` UI shows again after transaction has been completed.  

OS: Android (Oneplus A3000)
App version: 0.2.3
Transaction: Transfer ASTR (EVM) (native is fine)

https://www.loom.com/share/da6d0c2c203e45bf9bbd7fa30e926359

**Comment by NamPhamc99** [comment]
It's working correctly on the device that we use, here are the videos of the test cases
https://drive.google.com/drive/u/2/folders/12s1DGrJEjDIYgnM-d85moiWhCyRqCa8k

Device: Xiaomi Mi 8 Lite - Android 10

**Comment by impelcrypto** [comment]
@sirius651 @Kahonnohak @bobo-k2 @hoonsubin @togamamora @gluneau 

> It's working correctly on the device that we use, here are the videos of the test cases. Can you test it with another device perhaps ?

I'd like to seek your help for testing SubWallet mobile app on our portal especially for Android.

Staging URL: https://astar-portal-wheat.vercel.app/

**Review by impelcrypto — APPROVED** [review]
I've tested on iOS. LGTM

**Comment by sirius651** [comment]
@NamPhamc99 Hi, regarding android, is this only for extension? not native app?

**Comment by NamPhamc99** [comment]
Hi @sirius651, i'm not sure i understand your question. Can you be more specific ?

**Comment by impelcrypto** [comment]
@sirius651 If I understand correctly, we can test it on the Android native app.
https://play.google.com/store/apps/details?id=app.subwallet.mobile

**Comment by NamPhamc99** [comment]
> @sirius651 If I understand correctly, we can test it on the Android native app. https://play.google.com/store/apps/details?id=app.subwallet.mobile

yes you can download it from Play Store to test it out if you want

**Comment by sirius651** [comment]
> > @sirius651 If I understand correctly, we can test it on the Android native app. https://play.google.com/store/apps/details?id=app.subwallet.mobile
> 
> yes you can download it from Play Store to test it out if you want

Approved. confirmed that works well on android

**Comment by NamPhamc99** [comment]
Hello @impelcrypto, is there any new update regarding this PR ? Do we have to wait for the other 5 reviewers to approve ?

**Comment by impelcrypto** [comment]
Hi @NamPhamc99, I've merged this PR. Please take note that we are going to deploy the latest main branch to the production page (https://portal.astar.network/) next Monday.

**Comment by NamPhamc99** [comment]
Thank you @impelcrypto

**Pull request merged**
