### PR TITLE
hotfix: merge release-hotfix to main

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* merge hot-fix to main
  * ref: https://github.com/AstarNetwork/astar-apps/pull/795

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by impelcrypto** [comment]
I'm fixing conflicts in this PR https://github.com/AstarNetwork/astar-apps/pull/800

**Review by bobo-k2 — APPROVED** [review]

**Comment by Kahonnohak** [comment]
Is this the ledger one?

**Comment by impelcrypto** [comment]
@Kahonnohak 
Yes, this is a PR that merge the hotfix branch to main.

**Review by Kahonnohak — APPROVED** [review]
LGTM

**Pull request merged**
