### PR TITLE
Fix/release v0.0.22

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**
- Can the ‘s’ not be separated from ‘wallets”?
- Need improvement on the appearing and disappearing sequence/effect of the wallet & network selection menus.
- Error styling for the light theme is not implemented.

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
@sirius651 

Thank you! I think the font-weight is different.

in the Asset page, it's classed and translatable. Is this the same format? I also notice the styling is different. Just make it easier to have the same styling when we want to replace all to Astar UI?


スクリーンショット 2023-03-13 11 32 12

**Comment by Kahonnohak** [comment]
Thanks again @sirius651 

- The wallet/network modals are super - thank you for the fix!

- For the toaster, could you bring the last word to the next line when the width is not enough (without changing the width) just like an article? That problem will always happen otherwise. 

dApp staking only supports Substrate wall
ets
->
```
dApp staking only supports Substrate 
wallets
```

**Comment by sirius651** [comment]
스크린샷 2023-03-13 오후 11 29 28

Fixed above things (adjust styling as you made , modified css on toast msg). please check again @Kahonnohak

**Review by Kahonnohak — APPROVED** [review]
Thank you! LGTM!

**Review by impelcrypto — APPROVED** [review]

**Pull request merged**
