### PR TITLE
feat: phala integration

### PR DESCRIPTION
**Pull request by kingsleydon**
**Pull Request Summary**

> Integrate Phala chain, allow transferring PHA and ASTR between Phala and Astar

**Check list**
- [x] adds new feature

Changes refer to https://github.com/AstarNetwork/astar-apps/pull/552, tested in local environment.

### CODE REVIEW

**Comment by tolak** [comment]
@kingsleydon Should we change this PR to ready view?

**Review by impelcrypto — CHANGES_REQUESTED** [review]
I got this error when I deposit ASTR from Phala.

image

**Comment by impelcrypto** [comment]
Nvm, the error is because I don't have any PHA token in my account. Can I have some PHA for testing? 45eJ673uMiaK8Yri5zeXyirQcV9HRYqnpfeBijzyme858wWF

**Review by impelcrypto — APPROVED** [review]
LGTM

**Comment by sirius651** [comment]
I've also tested on Khala-Shiden with PHA, works well

**Review by sirius651 — APPROVED** [review]

**Pull request merged**
