### PR TITLE
docs: update zh translation

### PR DESCRIPTION
**Pull request by coin98team002**
**Pull Request Summary**

Update the zh translation

**Check list**

- [X] documentation changes

**This pull request makes the following changes:**

**Changes**

- Update the zh translation

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]
LGTM, Thanks for your contribution!

**Review by gtg7784 — APPROVED** [review]

**Comment by impelcrypto** [comment]
@coin98team002 there is a build error, could you run 'yarn format' to lint the json file?

**Review by bobo-k2 — APPROVED** [review]

**Comment by gtg7784** [comment]
Hi @coin98team002 can you please run the format script and push it to this branch to make it build?

**Comment by gtg7784** [comment]
Hi @coin98team002 seems you are busy so I created follow-up PR (https://github.com/AstarNetwork/astar-apps/pull/1413) to merge your contribution.

Thank you for the contribution, I'll close this PR and follow #1413

**Pull request closed without merging**
