### PR TITLE
Add Gridlock Wallet to connection options

### PR DESCRIPTION
**Pull request by rares-munteanu-gl**
**Pull Request Summary**

Added the Gridlock Wallet logo and connection options.

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [x] tested on mobile devices

**This pull request makes the following changes:**

Added logo file and modified the supported wallets objects.

**Changes**

- Only changed src/config/wallets.ts file and src/hooks/helper/wallet.ts

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @rares-munteanu-gl 
Please refer to [this guide](https://docs.astar.network/docs/build/builder-guides/integration_toolings/add-wallets-to-portal#requirements-for-creating-a-pr) and submit required links and staging URL. Thanks.

**Comment by rares-munteanu-gl** [comment]
Hi @impelcrypto 

Here is the videos link : https://drive.google.com/drive/folders/1y78pD4i9bDxEMuW12D1YCh-nQmsDZYCf?usp=sharing

Here are the tx links : 
Native token transfer Astar : https://astar.subscan.io/extrinsic/0x8d1772f82b6676721a47b6cf44c8259d5bad90b3894f98da3897cad2cd853b89

dApp Staking Shibuya : https://shibuya.subscan.io/extrinsic/0x9ecaa0bc571b85bedbc0d49182e5b443cd554b48a9ec01d46c4144d0492ab271

dApp Unbound and unstake Shibuya : https://shibuya.subscan.io/extrinsic/0x71fcbb8e13c20253b6366ee5e503b27219bb2315dcea378db2deca84bd1d1198

dApp Nomination Transfer Shibuya : https://shibuya.subscan.io/extrinsic/0x9425017c45c5ec6df36b515a405cb6971d99f8e6fc4e58c46714e2c097042a1a

dApp Withdrawal Shibuya : https://shibuya.subscan.io/extrinsic/0x72fa6e2f8bf6a194e92ec4ef753aad9807dabe1bb3e4d4aba2532374a96ccd1b

XCM transfer DOT -> Astar Native : https://astar.subscan.io/xcm_message/polkadot-e67c0b07df147e2810c35e152881728aa3049b77

XCM assets transfer : https://astar.subscan.io/extrinsic/3575287-2

XCM transfer Astar Native -> DOT : https://astar.subscan.io/xcm_message/polkadot-97099539319d28d30c7fa5afc3630059fd13ecde

Here is the link to deployed app to vercel : [astar-portal-i3kh0gsog-rares-munteanu.vercel.app](https://astar-portal-i3kh0gsog-rares-munteanu.vercel.app/)

For some reason this link doesn't work on mobile devices ( maybe because some settings from vercel ). I used the production link for testing : [astar-portal-sigma.vercel.app](https://astar-portal-sigma.vercel.app/)

Thanks.

**Comment by impelcrypto** [comment]
Hi @rares-munteanu-gl 
Could you share with me how to open a browser or change the address in the Gridlock app?

**Comment by rares-munteanu-gl** [comment]
Hi @impelcrypto.

The url in Gridlock app cannot be changed. It points only to https://portal.astar.network/.

The requested transactions were all tested in our dev environment using the provided changes in the astar portal pr.

**Comment by impelcrypto** [comment]
I see, but in that case we can't test it before merging this PR.

**Review by impelcrypto — APPROVED** [review]

**Comment by rares-munteanu-gl** [comment]
@impelcrypto 

We can setup a staging build for testing purposes ( on android ) for you to test the changes.

**Comment by impelcrypto** [comment]
That would be great!

**Comment by rares-munteanu-gl** [comment]
Great. Please share your gmail account to be invited once the build is ready.

**Comment by impelcrypto** [comment]
rswkure@gmail.com

**Comment by rares-munteanu-gl** [comment]
@impelcrypto invited. 

https://play.google.com/apps/internaltest/4701608610088013537

**Comment by rares-munteanu-gl** [comment]
@impelcrypto 

We also shared an apk file with you on your gmail account. Please use that one for future installs for testing.

**Comment by impelcrypto** [comment]
I've tested sending ASTR in the staging app and it worked. @bobo-k2 @sirius651 @Kahonnohak @niklabh @gluneau Please review this PR when you are available.

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
