### PR TITLE
feat: added xcm withdrawal UI

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* added withdrawal UI for EVM and Native accounts ([Demo](https://www.loom.com/share/3ef3c028b1ab42a78d69261e4df5d8f4))
* merge this PR once both EVM and Native withdrawal functions are implemented (advised by @Kahonnohak )

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [x] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Progresses**

- [x] add the withdrawal UI
- [x] implement the native withdrawal logic
- [x] implement the EVM withdrawal logic

**This pull request makes the following changes:**

**Adds**
* withdrawal logic for Native transaction (Shiden -> Kusama)
* withdrawal UI (Parachain ->Relaychain )
Native
image

EVM
image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
it would be good to add how to find Kusama/Dot address. But at the moment we don't have anything to link but I'll ask Ryo to create a section something like; https://wiki.acala.network/get-started/get-started/karura-account/check-address-for-different-chains

 
スクリーンショット 2022-05-26 15 23 41

**Comment by impelcrypto** [comment]
@sirius651 
pushed, please pull the latest branch.

**Comment by sirius651** [comment]
Current Status: Finish to implement withdrawal process for native asset, checked that it works on Shiden for now. (SDN > KSM). please double check that. @impelcrypto @Kahonnohak

**Comment by Kahonnohak** [comment]
We need to explain the risk of Existential Deposit but the text is not suitable for this Withdraw. If you could add the tooltip here I'll ask someone for copywriting.
スクリーンショット 2022-05-30 11 49 40

**Comment by impelcrypto** [comment]
@Kahonnohak 
Sure, I can add a tooltip for you.

**Comment by Kahonnohak** [comment]
@sirius651 
I'm trying to withdraw DOT in both above 1 and less than 1 but Mordal doesn't seem to be working.. Is it ready to test?

**Comment by sirius651** [comment]
> @sirius651
> I'm trying to withdraw DOT in both above 1 and less than 1 but Mordal doesn't seem to be working.. Is it ready to test?

as I commented, I didn't test DOT-ASTR, works only in Shiden. and when I checked that, there's no withdraw extrinsic call in Astar chain. it seems not ready now.

**Comment by sirius651** [comment]
Oh I forgot sending PR based on this branch, just pushed the codes. sorry about that. I'll send PR as next

**Comment by Kahonnohak** [comment]
Ah OK, that means should I wait for testing?

**Comment by sirius651** [comment]
> Ah OK, that means should I wait for testing?

I mean, in this PR, you can test native asset(KSM) withdrawal in shiden(SDN>KSM). for Astar chain or EVM withdrawal, I'll create another PR based on this branch

**Comment by Kahonnohak** [comment]
@sirius651 
I still cannot get it work. the button is not working or EVM doesn't come up... I've tried chrome Mac and firefox
- KSM address
- deposit is ok in both accounts
スクリーンショット 2022-05-31 1 02 44

**Comment by sirius651** [comment]
> @sirius651 I still cannot get it work. the button is not working or EVM doesn't come up... I've tried chrome Mac and firefox
> 
> * KSM address
> * deposit is ok in both accounts
> 
> スクリーンショット 2022-05-31 1 02 44

@Kahonnohak didn't get started EVM withdrawal. as discussed yesterday, the core part not implement yet  https://github.com/AstarNetwork/astar-frame/pull/57

**Comment by Kahonnohak** [comment]
@sirius651 oh I'm so sorry, totally mixed them up!

**Comment by Kahonnohak** [comment]
Hi, transfer was lovely!! I haven't tested with multiple environment and will do when EVM is ready.

UI issue here; because we didn't manage the UI before launch and skipped details, now the dropdown looks not good when there is only one option. We are going to move on to a new UI, wider and more complex transfer modal (dropdown will be separated from the main modal) so no need to make a lot of effort here but could you easily add a border around it?

スクリーンショット 2022-05-31 11 34 46

スクリーンショット 2022-05-31 11 34 59

**Comment by Kahonnohak** [comment]
Thanks @impelcrypto

**Comment by impelcrypto** [comment]
@Kahonnohak 
Updated.

https://gyazo.com/e02418e0b95c9b19e8897f86bc771d18

image

image

@sirius651 Please pull the latest branch.

**Comment by impelcrypto** [comment]
@sirius651 
Merged main branch and fixed conflicts. Please pull the latest branch.

**Comment by sirius651** [comment]
I have a question regarding UX process for transaction confirm.
Is it better to show the confirm hash right away and update the balance at the time of confirmation(8~12s), or show the loading bar until the confirmation is completed? 
There is a possibility that it can be seen as a bug depending on the user, so a specific guide is needed.
@Kahonnohak @impelcrypto

**Comment by Kahonnohak** [comment]
10s is too long to wait for the hush. I understand your concern though, people usually look for this confirmation than actual balance so I would leave it as it is until more concern is raised.

**Comment by impelcrypto** [comment]
@Kahonnohak @sirius651 
Let me try to improve this.

**Comment by impelcrypto** [comment]
@sirius651 
Pushed https://github.com/AstarNetwork/astar-apps/pull/455
CC: @Kahonnohak

**Comment by Kahonnohak** [comment]
Withdrawal works!! 

Regarding the loading, it takes a lot longer than depositing, does it normal behaviour?  Otherwise agree with you both to have loading while waiting the confirmation:)

- One small thing, I get an error in the middle of loading. But the transaction goes through. Would you get rid of this?  

- I'll ask Ryo if he can prepare for "how to find your Kusama address" in time. I think we do need it.

Thank you!

https://gyazo.com/834264a4e18d5681f28ec14f4c447dde

**Comment by impelcrypto** [comment]
@Kahonnohak 
Yes, it is normal that it takes some time to complete the transaction. 

> One small thing, I get an error in the middle of loading.
Fixed, please test it again.

**Review by Kahonnohak — APPROVED** [review]
Great Work!

**Comment by hoonsubin** [comment]
Screen Shot 2022-06-24 at 6 58 28 PM

```
popup.js:2 Error: submit transaction to pool failed: Pool(InvalidTransaction(InvalidTransaction::Custom(3)))
    at i.handleResponse (popup.js:928:761536)
```

I'm getting this error when I try to withdraw from EVM account

**Comment by hoonsubin** [comment]
https://user-images.githubusercontent.com/40356749/175609148-72a01ff2-2613-4372-93f5-8595be97ace1.mp4

This may not be a direct issue with the current PR, but this problem is blocking me from reviewing the withdraw function since I can't use it with Talisman (which, I assume a lot of users will use after the Crowdcast we had together).

Please look into it and see how long it will take to fix. If it takes too long, I will test it with the good old fashion MM.

**Comment by impelcrypto** [comment]
@hoonsubin  Fixed, please try it again.

@sirius651 It looks like `Talisman` required [a gas parameter](https://github.com/AstarNetwork/astar-apps/pull/417/commits/648accbedbea2f5d3def30625e4d6f924a46ac6c#diff-aa82075914ca04a74eafda59499d504733c8ab85ddb039b43e5aa33e963cb1b9R92) that was calculated from the `estimateGas` function into the `sendTransaction` object. I've refactored `useXcmEvm.vue` file as well.

image

**Comment by impelcrypto** [comment]
@hoonsubin 
> https://github.com/AstarNetwork/astar-apps/pull/417#issuecomment-1165768326

Perhaps you might want to check the authorization configuration in your talisman extension. It is working as expected on my end.
https://www.loom.com/share/c0becba55e604b908bcabc4cfc1a4d2d

**Comment by Kahonnohak** [comment]
Hello, @impelcrypto  could we add "Where can I find my Kusama address" with this ticket, please??  Would like to link to `https://docs.astar.network/xcm/faq#q-where-can-i-find-my-polkadot-kusama-addresses`.


Screenshot 2022-06-27 at 10 35 24

**Review by hoonsubin — APPROVED** [review]
OMG it works!!!

Great work!

**Pull request merged**
