### PR TITLE
APR calculations at given block + voting period ad

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

- APR staker and bonus calculations for any given block (moved existing APR calculations to `DappStakingService` to make at block calculations easier)
- Update tokens to be burned calculation to calculate for any block 
- Voting period add
image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]
Maybe add some spaces of margin below the Your Rewards panel?

image

**Comment by Kahonnohak** [comment]
@bobo-k2 

I just realised I did not see the staking page

- Could we have the same background?
- Would you remove the white back ground so its not doubled
- Can we open up on staking page like this, since it does not need to be folded?

Screenshot 2024-06-11 at 09 21 26
Screenshot 2024-06-11 at 09 21 13

**Comment by Kahonnohak** [comment]
@impelcrypto Ayumi has already worked on Mobile please check on Bobo's main PR (Styling is merged)

> Maybe add some spaces of margin below the Your Rewards panel?
> 
> image

**Comment by impelcrypto** [comment]
Checked and looks good!

**Review by Kahonnohak — APPROVED** [review]
LGTM

**Pull request merged**
