### PR TITLE
fix: avoid loading the portal twice on the first visit

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: avoid loading the portal twice on the first visit

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Release notes:**

* fix: avoid loading the portal twice on the first visit

**This pull request makes the following changes:**

**Fixes**

=Before=
https://i.gyazo.com/adce398cda4191f9ff655c9d0e73ea6c.mp4

=After=
https://www.loom.com/share/881347f0e2a74cd89fd8ee8a7109aef2

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you!! 
At the very very first connection, it still loads twice on Chrome and Brave, Firefox is good! But it is only the very first and if I go back and load it is super smooth. Shall I approve?
https://gyazo.com/7bc3e04c598717d7f3d077585135f498

**Comment by impelcrypto** [comment]
@Kahonnohak 
That's weird... both Chrome and Brave works fine on my end.

https://www.loom.com/share/619793af84a5429cbe8de983c81e5447
https://www.loom.com/share/881347f0e2a74cd89fd8ee8a7109aef2

**Comment by Kahonnohak** [comment]
yes it is only the very first so if others approve I think it is great. It was such an annoying little bug! Please also apply this to Astar NFT once merged:)

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Review by Kahonnohak — APPROVED** [review]
LGTM

**Review by sirius651 — APPROVED** [review]

**Pull request merged**
