### PR TITLE
feat: added Stats section on the dApp page

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: added Stats section on the dApp page
* refactor: refactored code around `chart` UI

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
* feat: added Stats section on the dApp page
image

@bobo-k2 @Kahonnohak Please advise if the words in the tooltip is incorrect
image

image

### CODE REVIEW

**Comment by impelcrypto** [comment]
Hi @niklabh It looks like something wrong with RPC tests, please help take a look.

image

**Comment by Kahonnohak** [comment]
Thanks Roy,

Can the stats go responsive util the max width? We would us
スクリーンショット 2022-11-23 10 46 25
e the same width for the Asset page when we make changes.

About tooltip

I think Unique Active Users are fine as it is and Number Of Calls, I would rather say "Number of Transactions" but let me ask others.

**Review by niklabh — APPROVED** [review]

**Comment by impelcrypto** [comment]
@Kahonnohak I've updated the page as per your request. Please take a look again.

**Review by Kahonnohak — APPROVED** [review]
Thank you LGTM!

**Review by bobo-k2 — APPROVED** [review]
Great work. LGTM

**Review by sirius651 — APPROVED** [review]

**Pull request merged**
