### PR TITLE
index.ts-it Update

### PR DESCRIPTION
**Pull request by VasaKing**
**Pull Request Summary**

This is the updated version of the Italian language of the Portal

### CODE REVIEW

**Review by impelcrypto — CHANGES_REQUESTED** [review]
The words should be used by single quotes instead of double quotes. Also, please make sure linting your code by `yarn lint --fix` and run it locally before pushing commits.

**Comment by VasaKing** [comment]
Ok , I will modify and test it out on my Github account before pushing it again :)

**Comment by gluneau** [comment]
I'm suspicious that these two keys have been renamed
- from `nativeWallets` to `nativeAccount`
- from `evmWallets` to `evmAccount`

I can see right here that it is still Wallets and not Account https://github.com/AstarNetwork/astar-apps/blob/main/src/i18n/en-US/index.ts#L180

Either change it in all the files or undo @VasaKing

**Review by gluneau — CHANGES_REQUESTED** [review]
https://github.com/AstarNetwork/astar-apps/pull/1100#issuecomment-1920461991

**Comment by Kahonnohak** [comment]
Hey what's the problem here @VasaKing?  You left too long that it has conflict.

**Pull request closed without merging**
