### PR TITLE
fix: Removed the `Total Earned` column for MVP

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: Removed the Total Earned column for MVP
  * @sirius651 We have to fix the styling(both mobile and laptop) on the My dApps panel   CC: @bobo-k2 @Kahonnohak   

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Fixes**
* fix: Removed the Total Earned column for MVP
image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thanks!

BTW can we change the denomination of the staked tokens?
Screenshot 2022-10-21 at 11 21 08

I think 100,000,000 ASTR would be better...

**Comment by Kahonnohak** [comment]
I just noticed the header says "Our dApps" which is wrong. It is "dApp Staking" could you also fix this please?

**Review by sirius651 — COMMENTED** [review]
isn't mobile view the scope of this PR?
스크린샷 2022-10-22 오전 9 42 30

**Comment by impelcrypto** [comment]
@sirius651 The sidebar is always turned on whenever I open the app by localhost (only under localhost). Could you resolve this behavior? 
https://gyazo.com/e65c212027093d8bac19f51982a1f9c3

**Comment by sirius651** [comment]
> @sirius651 The sidebar is always turned on whenever I open the app by localhost (only under localhost). Could you resolve this behavior?
> https://gyazo.com/e65c212027093d8bac19f51982a1f9c3

Oh I couldn't see the behavior. how can I reproduce this?

**Comment by impelcrypto** [comment]
@sirius651 Please refer to [this](https://www.loom.com/share/39ccfd1125c944d6a85bfd04c3ccc16b) video

**Comment by impelcrypto** [comment]
@sirius651 I've bound data for mobile devices ([commit](https://github.com/AstarNetwork/astar-apps/pull/544/commits/efa7f79a0cf82d584deb962945b415261e05590c)).

image

**Comment by impelcrypto** [comment]
@sirius651 
> The sidebar is always turned on whenever I open the app by localhost (only under localhost). Could you resolve this behavior?

Can we close this PR first?

**Comment by sirius651** [comment]
yes, but unfortunately, I couldn't reproduce at all on my end even in localhost. what's your environment in detail?

**Comment by impelcrypto** [comment]
@bobo-k2 are you able to reproduce the issue mentioned in the comments above?

**Comment by bobo-k2** [comment]
> @bobo-k2 are you able to reproduce the issue mentioned in the comments above (under localhost)?

I can't reproduce

**Pull request merged**
