### PR TITLE
feat: added dapp page

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* added dApp page
  * e.g.: https://astar-apps--pr531-feat-dapp-page-v2-g3aifcks.web.app/#/astar/dapp-staking/dapp?dapp=0x992bad137fc8a50a486b5c6375f581964b4a15fc

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

image

localhost_8080_

image

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you!

Commented in below.
https://drive.google.com/drive/folders/13oz9W47c4-eKwO_K35HWoDex013KAPee

Screenshot 2022-10-11 at 09 03 08

The carousel icon :
carousel icon

Would like to keep images side to side without having the icon space for mobile, otherwise the images on mobile look quite small.

**Comment by Kahonnohak** [comment]
Hi sorry for being slow, my figma had a funny bug yesterday I could not get svg out of it but here they are.
carousel_arrow_left
carousel_arrow_right

**Comment by impelcrypto** [comment]
@Kahonnohak Fixed, please take a look.

**Comment by impelcrypto** [comment]
@Kahonnohak Updated, please take a look.

**Review by Kahonnohak — APPROVED** [review]
Thank you! LGTM!

**Pull request merged**
