### PR TITLE
feat: MetaMask Snap install page

### PR DESCRIPTION
**Pull request by gluneau**
**Pull Request Summary**

- Fixes a misspelling `initiatePolkdatodSnap` --> `initiatePolkadotSnap` and some styling lint
- Adds a new page to install the MetaMask Astar Snap
- Start testing here: http://localhost:8080/snap

image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thanks Greg

Is it your purpose to remove sidebar contents as well as header contents???

**Comment by gluneau** [comment]
Yes, because it would not even work before they complete the steps.  
Less to click, more chances they follow the flow.

**Comment by Kahonnohak** [comment]
Please make some changes

You cannot remove the side bar that really looks weird (you cannot remove index from index). Please bring the side bar back. 
- If users then press the button on the sidebar they should go back to the net work they were connected before
- If users don't have cache then give the wallet modal up when they connected to the asset page

please also change the wallet modal behaviour
- If user doesn't have Snap yet, bring the users to this page
- If user does have the Snap, that will connect

**Comment by Kahonnohak** [comment]
Hi @gluneau sorry but we have no one who can work on this, so lets then release with docs information and we can maybe come back next year.

**Comment by bobo-k2** [comment]
@Kahonnohak can we close this PR?

**Comment by Kahonnohak** [comment]
we sure can!

**Pull request closed without merging**
