### PR TITLE
feat: add GAME asset img and xcm data

### PR DESCRIPTION
**Pull request by 2075**
**Pull Request Summary**

GameDAO is a dappstaking and UCG participant.
The protocol uses the GAME token which is also an upcoming dapp staking reward.
GAME token has been added to Astar L1 with asset id '18446744073709551641'.
This PR will add XCM data and visual assets to add the token to the portal.

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

- add GAME token data to 'src/modules/xcm/token' info, with local asset id '18446744073709551641'
- add GAME token image to 'src/assets/img/token'

### CODE REVIEW

**Comment by 2075** [comment]
Question: how can the asset id show the name on Asset Hub:

image

Thank you!

**Comment by 2075** [comment]
Transfer Assets

Success

send 0.1 GAME
https://astar.subscan.io/assets/18446744073709551641

ASTAR

https://astar.subscan.io/extrinsic/0x762a46608b7636a362241f38c1500535a5c00e050f1a6bc90e9b1b0334dbb9a8

Confirm

0.1 GAME back
https://astar.subscan.io/extrinsic/0xe717005f09db08af493017b307ec4b4619f0da6b21a2144305882ac5e965d2f3

Balance 0 1 GAME

Transfer

to astar evm
https://astar.subscan.io/extrinsic/0x5b30f94eb9aace376cd77240d8efb5351c87de042872acafbc7031d0305d7ddb

**Comment by 2075** [comment]
Also we are wondering where to add the reference for the EVM balance, will they get consolidated in the assets list?

Live:
image

e.g. when having 0.5 GAME native and 0.5 GAME evm, will this be combined in the overview?

Thanks!

**Comment by codespool** [comment]
Hi @2075, thanks for the PR!
Can you send some GAME token to this address for testing? `0xc1388EB761bc7bB68C9AabBc2b7718DCB0b607Db`

> Also we are wondering where to add the reference for the EVM balance, will they get consolidated in the assets list?
No, only the current network's balance is shown.

**Comment by 2075** [comment]
> `0xc1388EB761bc7bB68C9AabBc2b7718DCB0b607Db`

Hey @codespool, like this?
https://astar.subscan.io/tx/0xae3d9c7c91984d2db440b7da050da81905e3be6264cb37278b48aaeb92ee8f54
Cheers!

**Review by codespool — APPROVED** [review]
Thank you, LGTM 👍

**Review by gtg7784 — APPROVED** [review]

**Pull request merged**
