### PR TITLE
Read APR from statistics API

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
- APR component
- fetch APR from statistics API

**To-dos**
> Implement unit tests. I tried to implement unit testing and stumbled upon so many issues. Lot of them has been solved, but last one gives me a headache

- [ ] (ex: add user list)

### CODE REVIEW

**Review by impelcrypto — APPROVED** [review]
LGTM
Please fix the unit test error (APR.spec.ts) in the next PR

**Comment by hoonsubin** [comment]
@bobo-k2 can you fix the unit test?

**Comment by hoonsubin** [comment]
Please resolve the merge conflicts

**Comment by hoonsubin** [comment]
I think this PR whent stale. Can I close it @bobo-k2?

**Comment by bobo-k2** [comment]
> I think this PR whent stale. Can I close it @bobo-k2?

Yes please

**Pull request closed without merging**
