### PR TITLE
E2E XCM 001, 003, 004 & 006

### PR DESCRIPTION
**Pull request by gluneau**
**Pull Request Summary**
 
- Standardize the ws ports in .yml files
- copy acala & polkadot chopsticks files locally
- change of ws endpoints for chopsticks
- add acala to the set of running nodes with polkadot relay
- extend getBalance to fetch any substrate balance on Astar
- add a function to roundUpAndTruncateBigInt for easy expect-toEqual
- E2E XCM 001, 003, 004, 006

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
Tests

### CODE REVIEW

**Comment by impelcrypto** [comment]
I got an error in XCM003.
Screenshot 2023-06-26 at 12 34 39 PM

**Comment by impelcrypto** [comment]
@sirius651 @bobo-k2 Please try to run the test and check the results.

```
npx @acala-network/chopsticks@latest xcm -p tests/chopsticks/astar.yml -p tests/chopsticks/acala.yml -r tests/chopsticks/polkadot.yml
```

```
yarn playwright tests/reserve-transfer-asset-xcm.spec.ts
```

**Comment by sirius651** [comment]
> @sirius651 @bobo-k2 Please try to run the test and check the results.
> 
> ```
> npx @acala-network/chopsticks@latest xcm -p tests/chopsticks/astar.yml -p tests/chopsticks/acala.yml -r tests/chopsticks/polkadot.yml
> ```
> 
>  ```
> yarn playwright tests/reserve-transfer-asset-xcm.spec.ts
> ```

I also got test failed in all of cases

**Review by bobo-k2 — APPROVED** [review]
LGTM all tests are passing with `yarn playwright:ci`

**Comment by impelcrypto** [comment]
Let's put `reserve-transfer-asset-xcm.spec.ts` file into `test_specs` folder

**Comment by impelcrypto** [comment]
@gluneau `build` is failed

**Review by impelcrypto — APPROVED** [review]

**Pull request merged**
