### PR TITLE
add cookie policy component

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

> Add cookie policy component

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

스크린샷 2022-06-16 오후 4 02 25

### CODE REVIEW

**Comment by sirius651** [comment]
I didn't styling yet. so please specify design for cookie policy banner @Kahonnohak

**Comment by sirius651** [comment]
스크린샷 2022-06-16 오후 10 00 40

updated styling as similarly in notion

**Comment by sirius651** [comment]
스크린샷 2022-06-17 오후 7 49 39

@Kahonnohak Fixed like above

**Comment by sirius651** [comment]
Hi, do you know what the error is while building on CI? @bobo-k2 @impelcrypto 
```
Run yarn
[5](https://github.com/AstarNetwork/astar-apps/runs/6936211701?check_suite_focus=true#step:4:6)
yarn install v1.22.19
[6](https://github.com/AstarNetwork/astar-apps/runs/6936211701?check_suite_focus=true#step:4:7)
[1/5] Validating package.json...
[7](https://github.com/AstarNetwork/astar-apps/runs/6936211701?check_suite_focus=true#step:4:8)
[2/5] Resolving packages...
[8](https://github.com/AstarNetwork/astar-apps/runs/6936211701?check_suite_focus=true#step:4:9)
[3/5] Fetching packages...
[9](https://github.com/AstarNetwork/astar-apps/runs/6936211701?check_suite_focus=true#step:4:10)
error An unexpected error occurred: "https://codeload.github.com/byterose/keccak/tar.gz/673e4409975bf472b289fcb3548679291fa4dbd1: Request failed \"404 Not Found\"".
[10](https://github.com/AstarNetwork/astar-apps/runs/6936211701?check_suite_focus=true#step:4:11)
info If you think this is a bug, please open a bug report with the information provided in "/home/runner/work/astar-apps/astar-apps/yarn-error.log".
```

**Comment by impelcrypto** [comment]
> https://github.com/AstarNetwork/astar-apps/pull/444#issuecomment-1158840010

I got the same error in the different PR today. 
@niklabh @hoonsubin Do you have any idea?

**Comment by niklabh** [comment]
some package using keccak might be broken

**Comment by Kahonnohak** [comment]
> @Kahonnohak Fixed like above

I believe this fix is not deployed yet because of the issue??

**Comment by impelcrypto** [comment]
@niklabh 
It is weird that the CI check result was 'no error' in https://github.com/AstarNetwork/astar-apps/pull/444/commits/0b8a7a5ce3c4b1015b7bbbf5a3d251d6e92555f7, but the error appears in https://github.com/AstarNetwork/astar-apps/pull/444/commits/1f9f97af4b2594e662cb565e0103d520cfe74bbd. https://github.com/AstarNetwork/astar-apps/pull/444/commits/1f9f97af4b2594e662cb565e0103d520cfe74bbd  was some styling changes only (there are no updates for packages).

**Comment by impelcrypto** [comment]
@sirius651 @bobo-k2 @hoonsubin 

I've resolved this issue by updating the keccak package. May I know the reason for selecting this("byterose/keccak#stream-update") specific version of keccak? Can we use the latest version(^3.0.2) instead? Or can we remove this package since it looks like this package isn't been used anywhere?

https://github.com/AstarNetwork/astar-apps/pull/445/commits/807636f3793c35c5e3a95b48a4c713ef2bbaa42f

image

**Review by hoonsubin — APPROVED** [review]
The component works

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Pull request merged**
