### PR TITLE
feat: bridge ERC20 tokens between L1 and L2

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: bridge ERC20 tokens between L1 and L2
* feat: fetch token icon

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

* feat: bridge ERC20 tokens between L1 and L2

Screenshot 2023-10-15 at 12 13 32 AM

image

*　feat: fetch token icon
image

### CODE REVIEW

**Comment by bobo-k2** [comment]
Remove icon is not aligned with others. Maybe to have Bridge option here for quick access (similar as we have for ETH)
image

I was able to click Bridge button multiple times. Maybe to disable the button after first transaction is initiated.
image

Also a weird thing happened to me. Managed to have Approve option instead Bridge. This has something to do with dot in the amount.
image

**Comment by impelcrypto** [comment]
@bobo-k2 
> Remove icon is not aligned with others. Maybe to have Bridge option here for quick access (similar as we have for ETH)

Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/974/commits/f9d857af3869a84afc0adea3ec9d9efa5ca0305a) commit

Screenshot 2023-11-09 at 1 12 10 PM

**Comment by impelcrypto** [comment]
@bobo-k2 
> I was able to click Bridge button multiple times. Maybe to disable the button after first transaction is initiated.

Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/974/commits/23555d218e6ec39bc8fc39b60d0a5bdedfe6285b) commit.

**Comment by impelcrypto** [comment]
@Kahonnohak  @bobo-k2 
I've changed to display both `Approve` and `Bridge` buttons here
image

**Comment by impelcrypto** [comment]
@Kahonnohak 
> Please can you show the token it has been selected from the Asset page please? At this moment ETH is the default and when I click any bridge button from the asset page take me to ETH token.

It takes more time to set logic.

**Comment by impelcrypto** [comment]
@Kahonnohak 
> Can you change the text size to 16px?

Fixed
image

**Comment by Kahonnohak** [comment]
Understood, okay lets keep that bridge button next to the asset and we will see. Great work!

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Review by gluneau — APPROVED** [review]
LGTM

**Pull request merged**
