### PR TITLE
Header style update

### PR DESCRIPTION
**Pull request by ayumitk**
**Pull Request Summary**

Update the header style

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**

276842552-eac18687-5d1c-41a3-a89f-b7d47b8ddec7

276842583-e68f3837-d13c-494e-8e1a-b8588b8cb689

**To-dos**

> \*Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Comment by ayumitk** [comment]
I've updated the header style and added 4 border gradients depending on the network user connect.

276855239-50695390-868a-4c5c-bf81-1ef52141becc

Screenshot 2023-10-22 at 10 43 52 PM

276855296-d8e9c304-c647-429a-ac4b-794632f27ce2

276855311-41f94a03-8c69-4ca1-9b82-3f608de5d2e3

**Review by gluneau — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
Hi 
please make those changes
- the colour border with key chain colour -> 1px (I know it was too tick but cannot really imagine until I see it on screen how tick it is!)
- could you please change the font size of the Network name 16-> 14px. 
- make the question (help) round
- have 8px paddings between the wallet and network buttons.

Thank you so much. Could this be merged to a PR (new Asset page PR)? so it won't go to main?

**Comment by ayumitk** [comment]
@Kahonnohak I updated all styles above, including the branch merging into.

> the colour border with key chain colour -> 1px

It might feel different depending on the theme. In dark mode, 1px border is enough thickness, while in light mode, we can not see the colour that much. Should we change the thickness to 2~3px for the light mode?

**Light**
Screenshot 2023-10-23 at 2 06 01 PM

**Dark**
Screenshot 2023-10-23 at 2 06 14 PM

**Comment by Kahonnohak** [comment]
True! thanks for suggestion. would be great if you could adjust the thickness. 3px is good! appreciated!

**Comment by ayumitk** [comment]
@Kahonnohak I've adjusted the bottom border thickness to 3px ([edbbcf8](https://github.com/AstarNetwork/astar-apps/pull/989/commits/edbbcf80c6af3814b7e954f0b380224380442076))

**Pull request merged**
