### PR TITLE
fix: updated checkbox condition for the EVM transfer

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: updated checkbox condition for the EVM transfer

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Fixes**

* fix: updated checkbox condition for the EVM transfer
  * since GMO and GATE accept deposits on the EVM network, we don't need a checkbox for native token transfer on EVM mode.
 
=before= 
image

=after=

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Hi, Looks good! one thing, it is usually kind of thing that a warning appears just for a second when moving to the transfer page. Could it be fixed?
https://gyazo.com/3c20895e9be76d2b1164c110d2dc0bcc

**Comment by impelcrypto** [comment]
@Kahonnohak Fixed in [this](https://github.com/AstarNetwork/astar-apps/pull/720/commits/bb7e6bc4913e45f0aeb207dd4c65a09fc0c0cbb1) commit. Please test it again.

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Comment by bobo-k2** [comment]
What will happen if user is sending EVM tokens to some other exchange beside GMO or GATE? Will his tokens be lost?

**Comment by Kahonnohak** [comment]
> What will happen if user is sending EVM tokens to some other exchange beside GMO or GATE? Will his tokens be lost?

Yes will be gone. When users input Native address there will be different warning. So my argument for the next step is, is this enough? 

スクリーンショット 2023-03-24 11 52 26

**Comment by impelcrypto** [comment]
>  EVM tokens 
@bobo-k2 Do you mean native token (like ASTR) on EVM networks? I don't think users want to send native token(EVM) to CEXs which haven't support depositing to EVM networks.

**Comment by bobo-k2** [comment]
> > EVM tokens
> 
> @bobo-k2 Do you mean native token (like ASTR) on EVM networks? I don't think users want to send native token(EVM) to CEXs which haven't support depositing to EVM networks.

That is exactly what I wanted to ask. So, at the moment only GMO and GATE supports ASTR tokens deposit to EVM?

**Comment by impelcrypto** [comment]
Yes

**Review by bobo-k2 — APPROVED** [review]

**Comment by Kahonnohak** [comment]
BTW it is prepared for that:)

スクリーンショット 2023-03-24 12 06 21

**Pull request merged**
