### PR TITLE
Fix padding on dapp top page

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

[> Fix padding on dapp top page](https://www.notion.so/astarnetwork/Fix-paddings-on-dApp-Top-page-d12366a4a3c44376b4c1fc96c11d9a4c)

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Hi Thanks, I forgot to mention other paddings...!

Desktop 1600+
- The hero paddings move which I don't like... could you make them 24px on both sides and the between, please.
スクリーンショット 2022-12-15 7 03 00

Responsive
- Once the padding went down to 16px then everything should do the same. 
スクリーンショット 2022-12-15 7 05 22

Mobile (wide)
- All should be 16px
スクリーンショット 2022-12-15 7 07 53

Thank you!

**Comment by sirius651** [comment]
> 
> Thank you!

Fixed in this [PR](https://github.com/AstarNetwork/astar-apps/pull/631/commits/0060f9073f0866e7ab6cda61f624b4e8b4b81c07) , could you check again?

**Comment by Kahonnohak** [comment]
Thank you! I'll review later X

**Comment by Kahonnohak** [comment]
The hero padding is not 24px yet.  Please check. But finally so much better thank you. Let's communicate more next time.
スクリーンショット 2022-12-15 16 31 34

**Comment by sirius651** [comment]
스크린샷 2022-12-16 오전 10 44 59

Fixed as flex-basis property for this. is it works for you?

**Review by Kahonnohak — APPROVED** [review]
Finally! So much better. Thank you!

**Review by impelcrypto — APPROVED** [review]
Amazing!

**Pull request merged**
