### PR TITLE
Add PEN and XLM tokens to Astar portal

### PR DESCRIPTION
**Pull request by b-yap**
**Pull Request Summary**

Add support for PEN and XLM asset

**This pull request makes the following changes:**

**Adds**

- PEN and XLM svg images
 - PEN and XLM xcm transfer support
 
 Here are the extrinsic transactions for PEN:
~https://astar.subscan.io/extrinsic/0xcacc02f33b8e6d74abb722504ae6f06e253d7d5db3891aac1f0074c8b6ca43da~
~https://pendulum.subscan.io//extrinsic/0xaf7feb3e6b71a1f6c50964e9c44305360027678c0b9254341d6b0ccfd6b83553~

~Test for minimum 0.1 PEN:~
~https://pendulum.subscan.io//extrinsic/0xfbdd784f2eb845a952a0fefcf5ae76428b42bd4eeffd43936f00e38d768eaafb~
Extrinsic transactions of PEN token  in order:
* Pendulum -> Astar: https://pendulum.subscan.io//extrinsic/0xcbfcc457735560cb384a0cca7f7f22cc90151b3f993629f77adf2fa825867e16
* Pendulum -> Astar: https://pendulum.subscan.io//extrinsic/0x59f0cd5a585ff03d9ebcc9ab3c456e588b0558b1f2788e45b0b6456b074069ae
* Astar to Pendulum:
https://astar.subscan.io/extrinsic/0x6d4db503dc5ca31e33a0ac9a7770dca92594ec3dea2b65d9dfd78e32b792bdc2

Extrinsic transactions of XLM token in order:
* Pendulum -> Astar: https://pendulum.subscan.io//extrinsic/0xd7218b8cb97ae3e37f7279d8eba8a5d692400cfbc789c7982a667ec1c9fa3559
* Astar -> Pendulum: https://astar.subscan.io/extrinsic/0xf3ee84928dcfde37d0aa5530c89e438513d1877d04c13cd5a48a4b7e0105ed91
* Pendulum to Astar: https://pendulum.subscan.io//extrinsic/0x3e403c13d74189c8e8a38cfc6a6ad8b0c83180a15d44adae728a94dc5aa9bd45

Vercel URL: ~[astar-apps-b-yap-bs-projects-fe8df2be.vercel.app](https://astar-apps-b-yap-bs-projects-fe8df2be.vercel.app/)~ https://astar-apps-bs-projects-fe8df2be.vercel.app/

### CODE REVIEW

**Comment by bobo-k2** [comment]
Thank you for the PR. Please send some test tokens to XLoLJBQoMPHMLXYhdFobSpH5GujRoUH8d1sUtaEtoBG7zaS

**Comment by gtg7784** [comment]
Hi @b-yap ! Thank you for contribute on our portal, can you send me PEN and XLM for testing it?

This is my Astar wallet address `WGeDwTxHVMnbzNS7xkKsxfrabvimPkF96eBa7uYYbTDzNiG` 

Thank you :)

**Comment by b-yap** [comment]
@bobo-k2 @gtg7784 Should I send test tokens to both accounts: 
`XLoLJBQoMPHMLXYhdFobSpH5GujRoUH8d1sUtaEtoBG7zaS`
`WGeDwTxHVMnbzNS7xkKsxfrabvimPkF96eBa7uYYbTDzNiG`
?

Or any of these 2?

**Comment by gtg7784** [comment]
> @bobo-k2 @gtg7784 Should I send test tokens to both accounts: `XLoLJBQoMPHMLXYhdFobSpH5GujRoUH8d1sUtaEtoBG7zaS` `WGeDwTxHVMnbzNS7xkKsxfrabvimPkF96eBa7uYYbTDzNiG` ?
> 
> Or any of these 2?

Please send it to both, We want to test it on each environment.

Thank you :)

**Comment by b-yap** [comment]
@gtg7784 XLM tokens transferred:
https://pendulum.subscan.io/xcm_message/polkadot-a01b30d8091ec0b61088d9ca2550049e55ba3bcc
https://pendulum.subscan.io/xcm_message/polkadot-3bb12bfa4fdb443eb5d38f444236875a33a10c84

**Comment by b-yap** [comment]
@gtg7784 PEN tokens transferred:
https://pendulum.subscan.io/xcm_message/polkadot-f1e76d4e05b44b43fedafbfc4e0ab8a51028edd0
https://pendulum.subscan.io/xcm_message/polkadot-b5ac12dd1ed6ef510e948cff74d255df1d36d337

**Comment by bobo-k2** [comment]
After selecting Pendulum network
image
I am XCM component dissapears. This doesn't happen for other networks. I don't see any error in console
image

**Comment by bobo-k2** [comment]
Hi @b-yap the new Vercel URL is asking me to authenticate 
image

**Comment by b-yap** [comment]
@bobo-k2 sorry for that. Updated: https://astar-apps-b-yap-bs-projects-fe8df2be.vercel.app/

**Comment by bobo-k2** [comment]
When I started testing I had 3 xcPEN on Pendulum. After that I made two transactions from Astar
 to Pendulum and UI is still showing 3 xcPEN
https://astar.subscan.io/extrinsic/0x7c1352ba3daba47a01ff1c7831c7880fd73cc56c8b6e6cce469ae85d61cc088d
https://astar.subscan.io/extrinsic/0xba4004fccbf2e0c064f0f9950e287de7f9fe90a177bdbd01062a1537039b6896
image


I transfered 1 XLM.s from Astar to Pendulum and UI still showing 0 XML.s on Pendulum
https://astar.subscan.io/extrinsic/0xff7e7c92686805d76377c7b78919951db82e186f561a567f77a86226911fd0b2
image
After reloading the portal shows 0.042 XML.s?!
image

**Comment by b-yap** [comment]
@bobo-k2,  Apologies for the long response.
 
 We updated the code and tested again in Vercel: https://astar-apps-b-yap-bs-projects-fe8df2be.vercel.app/.

I made a [first transfer of 1 PEN](https://pendulum.subscan.io/extrinsic/0xbd03b383da38863054c9a91734960e1ac2c9564a3278bc0eeeb74984f0cdd4fb); so your account should have 3.494 PEN:
Screenshot 2024-07-24 at 1 57 36 PM
( I made [another 1 PEN transfer](https://pendulum.subscan.io/extrinsic/0x178105d6da4588819bfc19d71c6d4433f73b5b32814a66b92388cbb9314b8538) so your account should have more. )

I am [about to transfer .1 PEN to my Astar account](https://pendulum.subscan.io/extrinsic/0x3f5db0fbfa6c2fddae148e85b718ca0906ca866848a2a457303fcf282f39e911); with my Pendulum account having 27,777.**6**7 PEN and Astar Account of **0.098** PEN.
Screenshot 2024-07-24 at 1 59 02 PM

After a successful transfer, it got updated with a value of **0.196** PEN
Screenshot 2024-07-24 at 2 00 04 PM

See my Pendulum account dropping at 27,777.**5**7 PEN
Screenshot 2024-07-24 at 2 00 14 PM


I [attempted to transfer back **.1 PEN**](https://astar.subscan.io/extrinsic/0x8708f70817e00ec65665830f9e366a96a5e80b2c367ddc7468bae10f7ce5ccba) from my Astar Account to Pendulum account: 
Screenshot 2024-07-24 at 2 17 35 PM

After a successful transfer:
Screenshot 2024-07-24 at 2 00 59 PM

**Comment by b-yap** [comment]
Moving this to draft, for now.

We identified that the minimum transfer amounts we use so far are not large enough to cover the XCM transfer fees charged on Pendulum. We are currently discussing which values we should use and will update the PR accordingly.

**Comment by b-yap** [comment]
XLM transfer: 
Beginning amounts:
Screenshot 2024-07-25 at 4 51 09 PM

Result after transferring **1.01 XLM Pendulum -> Astar**
Screenshot 2024-07-25 at 4 56 38 PM

Result after transferring **1.1 XLM Astar -> Pendulum**
Screenshot 2024-07-25 at 5 00 38 PM

Result after transferring **1 XLM Pendulum -> Astar**
Screenshot 2024-07-25 at 5 07 32 PM

**Comment by b-yap** [comment]
PEN transfer:
Beginning amounts:
Screenshot 2024-07-25 at 11 37 00 PM

Result after transferring 2.01 PEN Pendulum -> Astar:
Screenshot 2024-07-25 at 11 38 36 PM

Result after transferring 2 PEN Pendulum -> Astar:
Screenshot 2024-07-25 at 11 41 22 PM

Result after transferring 2.5 PEN Astar -> Pendulum:
Screenshot 2024-07-25 at 11 43 06 PM

**Comment by b-yap** [comment]
@bobo-k2 We have increased the minimum transferred amounts, thus gave you more XLMs and PENs to play with. 
Vercel link: https://astar-apps-bs-projects-fe8df2be.vercel.app/

**Comment by bobo-k2** [comment]
Hi @b-yap and thank you for the update. Another problem arise in the meantime. I believe this happens because outdated polkadot.js version. Please merge `main` into your branch. We uplifted polkadot.js to the latest version recently.
image

**Comment by bobo-k2** [comment]
Hi @b-yap now I am having different error. Did you try Vercel deployment?
image

**Comment by b-yap** [comment]
Hi @bobo-k2 
Not sure what happened in Vercel, my apologies. 

I redeployed again (doing `yarn` -> `yarn build` all over again):
Screenshot 2024-08-13 at 8 49 07 PM
https://astar.subscan.io/extrinsic/0x7a9ec7bb4776cb5baf986931d71e1a52ec626cd22731c2fda7215c91e0cd5649

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
Hi @b-yap 
Could you send some tokens to test? Thanks!
5H6DC1YjyD531FiGxPCpWY3WNJrp5kQ35xHm6wibKuFvWzKW

**Comment by prayagd** [comment]
@annatekl can you please get @impelcrypto the required funds?

**Comment by impelcrypto** [comment]
@annatekl 
Sorry but the amount of the xcPEN you sent is too low to test bridging tokens, could you help send maybe 20xcPEN? 

image

**Comment by annatekl** [comment]
> 5H6DC1YjyD531FiGxPCpWY3WNJrp5kQ35xHm6wibKuFvWzKW

Shall i send 20 PEN to this address?

**Comment by impelcrypto** [comment]
@annatekl yes pleased

**Review by impelcrypto — APPROVED** [review]
LGTM

**Comment by annatekl** [comment]
When do I expect the assets to be added to the portal view? @impelcrypto

**Comment by impelcrypto** [comment]
@annatekl 
Most likely the new version will be deployed next week

**Pull request merged**
