### PR TITLE
Update header component

### PR DESCRIPTION
**Pull request by sirius651**
**Pull Request Summary**

Update header component (including sidenavi for mobile )

스크린샷 2022-08-24 오후 11 14 04

스크린샷 2022-08-24 오후 11 13 49

### CODE REVIEW

**Comment by sirius651** [comment]
since there's conflicts on storybook. I'm trying to resolve that now. but you can start review on it. maybe start sidenavi for mobile first? @Kahonnohak 

here's the current note

- currently, looking the issue that backdrop filter on header is not working on the portal.
- regarding button state, updated the style in ui library (Buttons > Button) - https://main--625fa762a035be003a9814c1.chromatic.com/
- still working on animating for hover state on button

**Comment by sirius651** [comment]
@Kahonnohak could you check again about header component. I just set background and opacity for light and dark mode

light: `background: rgba(247, 247, 248, 0.8)`
dark: `background: rgba(25, 29, 31, 0.8)`

**Comment by Kahonnohak** [comment]
nice! Thank you!! I think the desktop header blur is good now:)

I forgot to mention sorry,

1) please make the border-bottom colour for the light theme Grey2 #e6e9ee. 

2) for the **mobile** I'll update my feedback soon.

**Comment by Kahonnohak** [comment]
Thanks Will,

Could you please look at the figma file again? It doesn't need to be transparent any more so changed the background as 100%.

1) background colour (header and navi are the same colour)

- Grey 8 for Dark
- Grey 1 for Light

2) border colour
- Grey006 #2C3335 for Dark
- Grey2 #e6e9ee for Light

3)please see the menu, could you add the background colour as default and blue when pressing

4) Please see the setting(Language and Theme)

5)Could you add a close text button at the bottom please.
(Colour changes to blue when pressing)

Thanks let me know anything you are unclear about.

**Comment by sirius651** [comment]
> Thanks Will,
> 
> Could you please look at the figma file again? It doesn't need to be transparent any more so changed the background as 100%.

does that mean we no more using backdrop-filter on the header like before?

**Comment by Kahonnohak** [comment]
please find Social media links here
https://docs.google.com/spreadsheets/d/1ZEQi0yWMfB-ipmOrMcwevoWlPU_3Nzk-EVH5FMK34NY/edit#gid=258798078

**Comment by sirius651** [comment]
@Kahonnohak  Fixed above. please check. and when I re-enter in Figma, the components in Header/sidenav seems throws away. where can I see this?

스크린샷 2022-08-29 오후 10 04 31

**Comment by Kahonnohak** [comment]
@sirius651 oops sorry seems now back to normal! Apologies for the slow reply

**Comment by sirius651** [comment]
> @sirius651 oops sorry seems now back to normal! Apologies for the slow reply

Hm , still not visible on my end in Astar Portal Design Language panel

**Comment by sirius651** [comment]
> @sirius651 oops sorry seems now back to normal! Apologies for the slow reply

oh I found that other panel. 
I put more details about side navi. please review on it

**Comment by Kahonnohak** [comment]
Thanks!

Please see below

1) the network and wallet button on Light theme has fill colour. could you remove the colour please? or Is this going to be a different ticket?

2) the pudding top here, please make it 24px

3) the padding-bottom here, please make it 40px

4) the link has not been updated please check this. https://docs.google.com/spreadsheets/d/1ZEQi0yWMfB-ipmOrMcwevoWlPU_3Nzk-EVH5FMK34NY/edit#gid=258798078

Otherwise all looks good! Thank y
05190F54-8350-4BD5-98DA-EA83476438DE
ou!
Screenshot 2022-08-31 at 11 22 14
Screenshot 2022-08-31 at 11 22 24

**Comment by Kahonnohak** [comment]
Thanks!

Noticed other things,

1) the screen wobbles
https://drive.google.com/file/d/1LZhaiVUr1NANDpyrGD8nF8x-RiYd-Oon/view?usp=sharing

2)Could you add the same tap effect (blue line) on the languages please?

3)broken layout

4)Header button (network) gone funny colour

I think you might be working in the middle of thes
Screenshot 2022-08-31 at 16 15 29
e, sorry in that case!

**Comment by sirius651** [comment]
> Hey everything is good but it lost the border, I liked how you did it rather than a drop shadow but now there is no border. Would you like to add the colour back in?
> 
> Also the social media links are not added yet.
> 
> Screenshot 2022-08-31 at 17 18 50

okay which color should I put in? (light/dark mode)
and, social link is working on my end (open new tab)

**Comment by Kahonnohak** [comment]
Link works on laptop but not on mobile metamask. cache maybe.

So if you don't remember how it was for the shadow and colour, I'll add it now and let you know

**Comment by sirius651** [comment]
> Link works on laptop but not on mobile metamask. cache maybe.
> 
> So if you don't remember how it was for the shadow and colour, I'll add it now and let you know

it seems work on my end (mobile metamask browser), and update the bottom border, if the color is not expected, let me know

**Comment by Kahonnohak** [comment]
Thanks @sirius651 Nice one! All done here from my side:)

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Review by hoonsubin — APPROVED** [review]

**Comment by impelcrypto** [comment]
It looks like the border color at the Connect button is a bit off.

Screenshot 2022-09-05 at 8 24 34 AM

**Comment by Kahonnohak** [comment]
> It looks like the border color at the Connect button is a bit off.
> 
I didn't notice this while checking but yes it looks like a bug, we didn't change the buttons in this PR.

**Comment by impelcrypto** [comment]
@sirius651 Perhaps due to this line of code? https://github.com/AstarNetwork/astar-apps/pull/490/files#diff-b7882d312898486d49f96a40ba85f6f09aa53a993f24fbcba4c917ba86228766R43

**Comment by sirius651** [comment]
> It looks like the border color at the Connect button is a bit off.
> 
Good catch. Fixed it. @impelcrypto @Kahonnohak

**Comment by impelcrypto** [comment]
With the current implementation, users have to click or tap on the icon in order to change the theme. How about changing the theme whenever users tap on the button instead of the icon (if it doesn't take too much time to update)? @Kahonnohak @sirius651 

https://gyazo.com/c9d0be1977bd252d84cedaf65eb5f87f

**Comment by impelcrypto** [comment]
> With the current implementation, users have to click or tap on the icon in order to change the theme. How about changing the theme whenever users tap on the button instead of the icon (if it doesn't take too much time to update)?

Oh, I found out that the button effects are not implemented on mobile devices, so it might not be necessary to update it.

**Review by impelcrypto — APPROVED** [review]

**Comment by Kahonnohak** [comment]
> Oh, I found out that the button effects are not implemented on mobile devices, so it might not be necessary to update it.

Yes, it is fine with mobile devices. I've ignored the small things. Let's move on:)

**Comment by Kahonnohak** [comment]
Can’t remember how you did it lol, would you find it or shall I say the shadow in css. It was nice though!

**Pull request merged**
