### PR TITLE
feat: updated `Top Metric` panel

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: updated `Top Metric` panel
  * feat: added ETA for the next era on the `Current Era` panel
  * feat added progress pie chart on the `Current Era` panel 
  * feat: displays APY on the `Stakers Rewards` panel 

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
=Before=

image

=After=

image

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
apologies to bring this but my bad that the mobile hero design has not been updated since some time ago on Figma. I wanted to make it two lines when it can so users can see more content and also to have APR/APY available.

Please see this and let me know if this can be possible. (basically keep the bottom padding same and make space in the middle) This is a Mobile view. The desktop view is good as as styling but I realise it is better to have APR come next to TVL.

スクリーンショット 2022-11-29 10 31 46

**Comment by impelcrypto** [comment]
@Kahonnohak 

> The desktop view is good as as styling but I realise it is better to have APR come next to TVL.

I've updated the order on the `TopMetric` panel as per your request. 

> I wanted to make it two lines when it can so users can see more content and also to have APR/APY available.

Let's make this change in the different PR.

**Comment by Kahonnohak** [comment]
Got it thanks, let me create the ticket then🙇

**Review by Kahonnohak — APPROVED** [review]
LGTM for desktop!

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
