### PR TITLE
hotfix: enabled zkEVM bridge for zKyoto

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* hotfix: enabled zkEVM bridge for zKyoto

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Changes**
* hotfix: enabled zkEVM bridge for zKyoto

### CODE REVIEW

**Review by gtg7784 — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
@gtg7784 Should I merge this PR and create the PR to main branch now?

**Comment by gtg7784** [comment]
> @gtg7784 Should I merge this PR and create the PR to main branch now?

before merging this PR, I want to merge https://github.com/AstarNetwork/astar-apps/pull/1340 first and make release and merge this PR
to prevent conflicts

**Comment by impelcrypto** [comment]
Ok, then you can merge this PR when it's ready

**Pull request merged**
