### PR TITLE
feat: updated connect wallet drawer

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* feat: updated connect wallet drawer
* feat: store the selected theme color to browser's local storage

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Release notes:**

- (ex: feat: updated dApp staking to V2)
- (ex: fix: modified styling bugs on the Assets page)

**This pull request makes the following changes:**

**Changes**

* feat: updated connect wallet drawer

image

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
All are super cool! Apart from one thing

When you are connected to EVM wallet and wanted to change the wallet and click on the drawer modal, not it is taken to here, but this doesn't look very obvious what users should do, could you show the same wallets list and change the button text to "change"

Screenshot 2023-04-26 at 10 45 01

change wallet

https://www.figma.com/file/s6xu63WKXosXjNCqOEknYv/Portal-V2?node-id=5315%3A133373&t=G6VPx8pLwTeNVGPM-1

**Comment by Kahonnohak** [comment]
One more comment please.

- Please change the box shadow to `-3px 1px 8px 0px #000c` and place the modal back in the place just below the header (position 96?)
- Also remove the radius, it looks like we have 6px but no need.

Thanks!

**Comment by impelcrypto** [comment]
@Kahonnohak Updated

**Comment by Kahonnohak** [comment]
Nice! Thank you!

Going back to the "disconnect" button, I still believe it would be better to have it here, otherwise people who are connected to Metamask would not see the button unless they click a substrate wallet. When a user is not conneted to any wallet, the button should be disabled.

What do you think?

Screenshot 2023-04-27 at 12 17 11

**Comment by impelcrypto** [comment]
@Kahonnohak updated

**Comment by Kahonnohak** [comment]
Hi Thank you! It's great! but super sorry I missed checking the light theme...

Light theme styling
- The background -> white
- The box -> no fill and border -> Navy 01, just like the Asset page
- Box-shadow - please change the colour 000-> 9999
Screenshot 2023-04-27 at 17 51 11

Behaviour
- When you can actually open two drawers - miner problem nothing important but spotted.
https://gyazo.com/b112b593977363dc1bc9b63d993d0d70

Dark theme 
- Same with the light theme could it all have the same style as the Asset page please?
- border 9da3ae and no fill for all boxes
- the space below "Native wallet" is too wide -> please remove the area on screenshot.
Screenshot 2023-04-27 at 21 34 56
Screenshot 2023-04-27 at 21 37 42

**Comment by impelcrypto** [comment]
@Kahonnohak Updated

**Comment by Kahonnohak** [comment]
Right, I see some areas get affected by the previous changes.

Dark theme
- The js wallet account select -> please use the same style (grey 3 border and no fill)
- Network drawer as well
Screenshot 2023-04-28 at 09 48 10
Screenshot 2023-04-28 at 09 48 42


Light theme
- Js wallet account select -> Same style applied please. (Navy 01 border and no fill)
- Network drawer, it lost the border colour but please apply the same style also.

Screenshot 2023-04-28 at 09 47 24
Screenshot 2023-04-28 at 09 47 38

Then I think we are done!!

**Review by Kahonnohak — APPROVED** [review]
Great work!!

**Review by sirius651 — APPROVED** [review]

**Pull request merged**
