### PR TITLE
styles: updated background color for the light theme

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* styles (light them): updated color variable
* styles (light them): updated background color for whole the page and the loading animation

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**
- (ex: Add feature A)

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you, I think this is good. Could you also apply FFF for the background on the **Transfer page** please? At first, it was white but I changed my mind but I think white is better.

**Review by sirius651 — APPROVED** [review]
Is this what you said earlier? set background-color as white for light them @Kahonnohak

**Comment by impelcrypto** [comment]
@Kahonnohak I've pulled the main branch and fixed conflicts. Please take a look at the staging URL.

**Comment by Kahonnohak** [comment]
Sorry for being so slow. Looks awesome and thank you for adjusting the padding!

**Review by Kahonnohak — APPROVED** [review]
Thank you!!

**Pull request merged**
