### PR TITLE
refactor: xcm feature refactoring

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* refactor: refactor code around XCM feature 

**Check list**
- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
* feat: added the `max button` on the XCM token transfer modal (native)
* feat: added the `speed configuration` UI on the XCM token transfer modal (native)

**Fixes**
* refactor: refactor code around XCM feature 
  * relaychain API instance was created 3 times due to using `useXcmBridge.ts` in `XcmCurrency.vue` ,`ModalXcmBridge.vue` and `ModalXcmTransfer.vue` before this refactoring
* fix: decimals calculation in `transferAsset` function
  * ref: https://github.com/AstarNetwork/astar-apps/pull/401#discussion_r875445698 

**Changes**
* fix: removed faucet button

**To-dos**
> *Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Comment by bobo-k2** [comment]
@impelcrypto I suggest to test and merge this PR after XCM release. It is a quite big and we have just a few hours 'till release and we don't have enough time to retest the whole feature. What do you think?

**Comment by impelcrypto** [comment]
> I suggest to test and merge this PR after XCM release. It is a quite big and we have just a few hours 'till release and we don't have enough time to retest the whole feature. What do you think?

sure, we need to test before merging, but I also want to test ASAP because this PR fixes the UI issue reported by @Kahonnohak .

**Review by hoonsubin — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
Checked and all good now!

**Comment by Kahonnohak** [comment]
@bobo-k2 
FYI I spent 4hours this morning to get the tests done again as Ambassadors are not interested anymore. So and one bug has been fixed since that I believe I can say go. If you feel not absolutely right then please do some tests.

**Comment by impelcrypto** [comment]
@bobo-k2 @sirius651 
Could you help test and review? I would like to merge this branch by tomorrow morning. 🙏

**Review by sirius651 — APPROVED** [review]

**Review by bobo-k2 — APPROVED** [review]
LGTM

**Pull request merged**
