### PR TITLE
Token allocation chart

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

image

**Check list**

- [ ] contains breaking changes
- [x] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**This pull request makes the following changes:**

**Adds**

- (ex: Add feature A)

**Fixes**

- (ex: Fix validation function)

**Changes**

- (ex: Change document B)

**To-dos**

> \*Feel free to remove this section if it's not applicable

- [ ] (ex: add user list)

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Looks good! 

So the main issue here is the Others still including some tokens from circulation supply. Please check

- According to our current Portal, Others should be 37% and Circulation should be 63%, those need to be dynamic. 
- In side of TVL it is nice if we know how much are unbonding but not "must" 
Screenshot 2023-09-01 at 09 09 38
Screenshot 2023-09-01 at 09 12 03

**Comment by bobo-k2** [comment]
> https://astar-apps--pr914-feat-token-chart-g9s5kgen.web.app



> Looks good!
> 
> So the main issue here is the Others still including some tokens from circulation supply. Please check
> 
> * According to our current Portal, Others should be 37% and Circulation should be 63%, those need to be dynamic.
> * In side of TVL it is nice if we know how much are unbonding but not "must"
> 
Yes, I am aware of that, but the issue happens because I am missing data for some token allocations. In reality, we have the following situation
37% - others
44% - tvl
4% - treasury
15% - unknown

I can add one more section to the chart for this unknown allocations, but not sure how to call it

**Comment by bobo-k2** [comment]
Added 4th segment. Also added two decimal point to percentage, otherwise percentage rounding make such mistake that at the end percentages sum up to 101%

image

**Comment by Kahonnohak** [comment]
Right!

1, Wording
In the pie chart
Not Circulation Supply -> Others
Not categorised (Other currently) -> Circulating
TVL-> Staking

The out side of the chart, right bottom
Circulating
Others

I added (s) to Other.

That should be aligned and okay!


2, Could you also adjust padding a bit, I could not see the exact numbers but just a little..

Screenshot 2023-09-01 at 16 05 13

**Comment by Kahonnohak** [comment]
Bobo, sorry, I was not looking at the Light theme.

Could you change the Other colour in the chart from Navy to Grey001 F7F7F8. It might be too light but I could not check the change in the inspect🙇

**Review by Kahonnohak — APPROVED** [review]
LGTM!

**Review by impelcrypto — APPROVED** [review]

**Review by gluneau — APPROVED** [review]
LGTM, it works.

**Pull request merged**
