### PR TITLE
Portal dashboard

### PR DESCRIPTION
**Pull request by bobo-k2**
**Pull Request Summary**

Created dashboard for the portal. I still have problem with collecting transactions data from Shiden so this chart will not be displayed.

I am using https://www.highcharts.com/ charting library which is used a lot in crypto space. We need to buy a license for the component,

image

image

**Check list**
- [ ] contains breaking changes
- [x] adds new feature
- [ ] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes

**This pull request makes the following changes:**

**Adds**
- portal dashboard

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thanks @bobo-k2 Could we make some changes please? 

1. Could you make TVL 100% width please? We don't have enough to fill the page so TVL can go bigger.
2. Colour of the chart: I couldn't get the colour from the code but 
- could you make the blue `#05B6FD` 100% please? 
- and the white lines at the back to be the same grey with the small numbers.
3. The boxes for Total Supply
- Padding at the bottom to be `32px`
- the font-weight for the tittle is `700` and the colour is `#B1B7C1`
スクリーンショット 2022-03-29 3 38 24

4. The boxes for the charts
- the font-weight for the tittle is `700` and the colour is `#B1B7C1`
- but the number remains #F7F7F8
- Please see below

スクリーンショット 2022-03-29 3 45 20

スクリーンショット 2022-03-29 3 45 28

**Comment by bobo-k2** [comment]
Hi @Kahonnohak, thank you for comments. I fixed styles, dashboard looks much better now. Please check.

**Comment by Kahonnohak** [comment]
@bobo-k2 
Thank you so much! It's gorgeous! I didn't have my energy left to review the light theme yesterday and have a little to ask if possible. I'll come back later. just wanted to thank you!

**Comment by Kahonnohak** [comment]
@bobo-k2 
Hi I decided to change the background colour ; it was a plan at the begging but wasn't sure if I should try when we have no time. But based on Sota's feedback let me try. i think it will be better.

Dark theme
- Then background colour to be `#222829` so please apply also in the charts.
- The background lines of the charts to be `#3C4649`
- The numbers and texts in the charts are #5F656F
- The line of the charts 2px `#0085FF`
- If you could try some gradients that would be a bonus.

Let me see the dropdown and I'll apply the colours.

Texts
the two charts at the top are
- Current Circulation Supply and Total Supply

Charts order 
- TVL
- Dairy Transactions
- ASTR token price

**Comment by bobo-k2** [comment]
Hi @Kahonnohak, please check the updated dashboard page. I apologize if I missed or misunderstood some points above

**Review by impelcrypto — APPROVED** [review]
LGTM

**Comment by Kahonnohak** [comment]
@bobo-k2 
Thank you! Styling is almost done, there are a couple of things I missed yesterday. I appreciate if you could look at them

Dark theme
**- Background colour**
- Mobile padding
- Could you remove the credit please (and place the filter)
- Please see the filter position

Light theme
-Mobile padding
 - Could you remove the credit please (and place the filter)
- Please see the filter position
スクリーンショット 2022-03-30 15 16 21


スクリーンショット 2022-03-30 15 04 19

**Comment by Kahonnohak** [comment]
@bobo-k2 
Plus, TVL is still not the expected number. We will need to look into it.

**Comment by bobo-k2** [comment]
I apologize for so many commits lately. @Kahonnohak I believe I fixed all styling issues. Please check.

**Comment by bobo-k2** [comment]
> @bobo-k2 Plus, TVL is still not the expected number. We will need to look into it.

TVL should be ok now

**Comment by Kahonnohak** [comment]
Amazing job!

If time allows - please check below
- Please change the default setting for 7days.
- Mobile "sm" could you make the filter width 100% (responsive)?
- Other fixed one, could you make the margin 16px please.
スクリーンショット 2022-03-31 15 39 36

**Comment by bobo-k2** [comment]
Thanks @Kahonnohak, I addressed your latest comments, please check

**Comment by Kahonnohak** [comment]
Thank you! One last thing! This is what I meant for mobile width 100%.

**Comment by bobo-k2** [comment]
> Thank you! One last thing! This is what I meant for mobile width 100%.
I am not sure I understand. Do you want me to remove margins?
image

**Comment by Kahonnohak** [comment]
I can see extra padding next to 1 year. Would it be possible to spread the paddings to each section?

**Comment by Kahonnohak** [comment]
> > I can see extra padding next to 1 year. Would it be possible to spread the paddings to each section?
> 
> This happens because width of all filter items is the same and text '1 year' is shorter than others.

Sorry the image wasn't uploaded. Small thing but it's iphone XR view. If it's not too hassle for you could you look at it please? But happy to approve if this is only my side.

スクリーンショット 2022-03-31 19 17 51

**Review by hoonsubin — APPROVED** [review]
LGTM

**Comment by impelcrypto** [comment]
Hi @bobo-k2,
Is there no more price data before 24-Feb (except the first few dates of the coin listing)? 

image

image

**Comment by bobo-k2** [comment]
> Hi @bobo-k2, Is there no more price data before 24-Feb (except the first few dates of the coin listing)?
> 
> image
> 
> image

I removed first days of listing because Sota asked me to do

**Comment by bobo-k2** [comment]
> > > I can see extra padding next to 1 year. Would it be possible to spread the paddings to each section?
> > 
> > 
> > This happens because width of all filter items is the same and text '1 year' is shorter than others.
> 
> Sorry the image wasn't uploaded. Small thing but it's iphone XR view. If it's not too hassle for you could you look at it please? But happy to approve if this is only my side.
> 
> スクリーンショット 2022-03-31 19 17 51

Aha, now is clear. please check now

**Comment by impelcrypto** [comment]
@bobo-k2 

> I removed first days of listing because Sota asked me to do

I thought the first few days means around 17 Jan ~ 26 Jan.
image

**Pull request merged**
