### PR TITLE
fix: maximum amount for nomination transfer

### PR DESCRIPTION
**Pull request by impelcrypto**
**Pull Request Summary**

* fix: maximum amount for nomination transfer
  * related: https://github.com/AstarNetwork/astar-apps/pull/707/files 
  * update the `leave minimum amount` for SDN to 1 instead of 10 

**Check list**

- [ ] contains breaking changes
- [ ] adds new feature
- [x] modifies existing feature (bug fix or improvements)
- [ ] relies on other tasks
- [ ] documentation changes
- [ ] tested on mobile devices

**Release notes:**

* fix: maximum amount for nomination transfer

**This pull request makes the following changes:**

**Fixes**

* fix: maximum amount for nomination transfer
  * max button for nomination transfer shouldn't consider `leaveAmount` value
  * amount shouldn't go below 0 after clicking the `max` button

=Before=

image

image

=After=

image

image

### CODE REVIEW

**Comment by Kahonnohak** [comment]
Thank you!

Funny but it works perfectly with Candy Girl but not with SushiTop?
https://gyazo.com/52b7420c16325174af4ee960f2257b5d

**Comment by impelcrypto** [comment]
@Kahonnohak @sirius651 
That's weird. It works fine on my end.
https://www.loom.com/share/848401c543874265a955b67fc30e9cf2

**Comment by impelcrypto** [comment]
@Kahonnohak @sirius651 
I can't reproduce the error. Could you try deleting cache and try it again?

**Comment by sirius651** [comment]
https://user-images.githubusercontent.com/1606820/228457275-35dd1f98-deaf-4630-b876-a7d3b5a0ecb8.mp4

here's the video of reproducing issue @impelcrypto

**Review by Kahonnohak — APPROVED** [review]
Thank you! Great work!

**Review by sirius651 — APPROVED** [review]
LGTM

**Pull request merged**
